### ISSUE TITLE
Boxes of air around dungeons

### ISSUE THREAD

**Issue by ImpulsiveLass** [cybercat-mods/gigeresque#104]
https://streamable.com/f2p64o
I feel this was reported already but it still happens when opening a new world,
I booted about 5 worlds and it occurs every time.
I'm not sure if this is being waited on until the large portions are added but I felt I should report it, I have no other mods installed.

**Comment by AzureDoom** [comment]
This only around rooms, will be fixed at a latter date as it's only looks.
