### ISSUE TITLE
Surgery Kit does not remove impregnation debuffs

### ISSUE THREAD

**Issue by ImpulsiveLass** [cybercat-mods/gigeresque#108]
If you use a surgery kit after being impregnated the weakness, hunger, and mining fatigue effects remain even after trauma expires
The blood particle effect will also appear indefinitely after a while https://streamable.com/30tbp9
The video also shows a better look at the acid issue and how it forces you to crawl when the hugger falls off
/effect clear doesn't remove them either

**Comment by AzureDoom** [comment]
This is a visual bug but this has been rewritten anyway due to the current usage not working on other entities.
