### ISSUE TITLE
[Fabric 1.19.2] Few issues

### ISSUE THREAD

**Issue by kingkuys2123** [cybercat-mods/gigeresque#110]
Gigeresque 0.5.2
AzureLib 1.0.2
SmartBrainLib 1.8
Fabric 0.14.14
Fabric API 0.73.2
Java 8 Update 351

## Missing Textures
**`Flowing Black Fluid`**
![image](https://user-images.githubusercontent.com/114457180/219227893-b12e1654-5288-4048-a6cf-ccd72094c6f2.png)

## Renames
I suggest renaming the [`Sitting Idol`](https://github.com/cybercat-mods/gigeresque/blob/285deb16e44677de2e4b48290eb73edfe2135a12/src/main/resources/assets/gigeresque/lang/en_us.json#L56) to `Sitting Alien Idol`

## Missing Lang Entries
**`Sitting Idol`**/**`Sitting Alien Idol`**
![image](https://user-images.githubusercontent.com/114457180/219228151-fbff555b-7b43-49c3-81d6-80b34339f96a.png)
**`Alien Sarcophagus`**
![image](https://user-images.githubusercontent.com/114457180/219228207-45d233d6-0024-4696-9178-365f3f7c1211.png)
**`Black Fluid`**
![image](https://user-images.githubusercontent.com/114457180/219229153-99819afb-5569-41f7-ae34-970c22909586.png)

**Comment by AzureDoom** [comment]
Hi!

Texture: This is fixed now!

Rename: This name is set for a reason that will be revealed in a later update. 

Missing Langs: Thanks! Added now!

This will be released in the next patch!
