### ISSUE TITLE
Xenos targeting creepers.

### ISSUE THREAD

**Issue by LatentDesire1** [cybercat-mods/gigeresque#112]
Xenos are targeting creepers and causing them to explode.

**Comment by AzureDoom** [comment]
This is intended. They will attack anything that's not another alien or a hugged/egg morphing entity. Save for bats but that's due to bats over spawning in caves.

**Comment by LatentDesire1** [comment]
Guess I'll just need to add something to deal with all the potholes this causes.  Possible fix would be giving xenos a stronger attack. Kind of weak at the moment where it would take 3-4 hits to kill an unarmored player.
