### ISSUE TITLE
gigeresque crash

### ISSUE THREAD

**Issue by joeballs12** [cybercat-mods/gigeresque#116]
[latest.log](https://github.com/cybercat-mods/gigeresque/files/10752316/latest.log)

**Comment by AzureDoom** [comment]
I see no crash here

**Comment by joeballs12** [comment]
[latest.log](https://github.com/cybercat-mods/gigeresque/files/10752436/latest.log)
updated log, i think

**Comment by joeballs12** [comment]
it crashes every time i try to start up mc

**Comment by AzureDoom** [comment]
Again, no crash is listed.

**Comment by joeballs12** [comment]
[2023-02-15-6.log.gz](https://github.com/cybercat-mods/gigeresque/files/10752550/2023-02-15-6.log.gz)
i think this might be the log, idk

**Comment by joeballs12** [comment]
but im being serious
it keeps saying:The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'gigeresque'!

**Comment by AzureDoom** [comment]
Ensure you are using the correct versions.
