### ISSUE TITLE
Crash without log on 1.19.2

### ISSUE THREAD

**Issue by benio1394** [cybercat-mods/gigeresque#117]
My game crash when loading with gigeresque 1.19.2 without crash report. I can only paste logs: https://pastebin.com/6t8sxrnL

**Comment by AzureDoom** [comment]
```
Mixin apply for mod lithium failed lithium.mixins.json:ai.task.memory_change_counting.TaskMixin from mod lithium -> net.minecraft.class_4097: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException PRIVATE @Overwrite method method_19546 in lithium.mixins.json:ai.task.memory_change_counting.TaskMixin from mod lithium cannot reduce visibiliy of PUBLIC target method
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PRIVATE @Overwrite method method_19546 in lithium.mixins.json:ai.task.memory_change_counting.TaskMixin from mod lithium cannot reduce visibiliy of PUBLIC target method
```
This is an issue with lithium, not Gigeresque.

**Comment by benio1394** [comment]
Crash is caused by mixin.ai.task.memory_change_counting that need to be false. You can add this script: https://github.com/CaffeineMC/lithium-fabric/wiki/Disabling-Lithium's-Mixins-using-your-mod's-fabric-mod.json to mod to disable this option when gigeresque is loading. Also it could probably fix similari issue with dark waters mod

**Comment by AzureDoom** [comment]
This would be Lithiums side to fix, not our mods as they changing the AI system

**Comment by benio1394** [comment]
Here is an issue in lithium github: https://github.com/CaffeineMC/lithium-fabric/issues/447
