### ISSUE TITLE
Alien vibration detection

### ISSUE THREAD

**Issue by Zesheir** [cybercat-mods/gigeresque#119]
Noticed a couple issues with detection, primary one being aliens are attracted to noised i.e footsteps of players in creative mode. Also, aliens seem to not really notice items dropping or projectile impacts as much. They seem to pathfind towards it for a split second before losing interest. And upon further testing, this seems to apply to a number of sounds, even more distant footsteps seem to attract in unreliably (still within 48 blocks).

**Comment by ImpulsiveLass** [comment]
The "losing interest" part may just be preoccupation

**Comment by Zesheir** [comment]
Possibly, but as far as I've been able to tell there isn't anything else they seem to be doing.

**Comment by ImpulsiveLass** [comment]
Any mobs or light sources near?

**Comment by Zesheir** [comment]
Tested with a platform up in the sky, alien wasn't fixated on any specific area of the platform so there shouldn't be anything on the ground he's somehow locked onto. Multiple sounds repeatedly seem to work, but it needs to be essentially continuous. A single block, step, or other sound, only results in maybe half a second of movement.

**Comment by Zesheir** [comment]
I have also noticed that aliens are attracted to the vibrations of other aliens, which results in them all clumping up together on a single block.
