### ISSUE TITLE
Chestbursters still bursting after use of surgery kit.

### ISSUE THREAD

**Issue by Ragabagayaga** [cybercat-mods/gigeresque#125]

**Comment by AzureDoom** [comment]
Yes, this is intended, you are removing it.

**Comment by ImpulsiveLass** [comment]
This is likely poorly explained, the bug is that surgery kits do remove a burtster but not the impregnation, you will still burst again later

**Comment by Ragabagayaga** [comment]
@ImpulsiveLad that is what I ment

**Comment by ImpulsiveLass** [comment]
After testing more, it would seem that a new burster isn't created but instead the mining fatigue, weakness, and hunger effects persist until you die with their time being written as 0:00 eventually. The blood particle effect also appears after a while and remains until death

**Comment by ImpulsiveLass** [comment]
(10x impreg and hugger speed for sake of time) 
https://streamable.com/ufofsz
