### ISSUE TITLE
Speed Effect not applied on Land (Facehugger)

### ISSUE THREAD

**Issue by WorldSpinAround** [cybercat-mods/gigeresque#127]
When you apply a speed effect to a facehugger, it does not have any changes when on land.
As soon as it touches water, however, the effect applies fully as it swim around.

It is mostly obvious when you give them a level 100 speed. Which makes me think the code handle a terrestrial facehugger differently regarding its movements.

**Comment by AzureDoom** [comment]
I am not able to reproduce this as the face huggers are moving faster for me both on land and in water.
