### ISSUE TITLE
Odd behavior, movement/crawl with some blocks?

### ISSUE THREAD

**Issue by WorldSpinAround** [cybercat-mods/gigeresque#129]
It is very hard to tell what happened or how to reproduce.
All I know is that the Alien tried to follow a villager, got into this spot with the trapdoor and block, and it started glitching out.

Warning: Epilepsy

https://user-images.githubusercontent.com/89668531/222430541-0d0901c9-c0fb-41bf-8ec1-a117472507e2.mp4

This one showcase the actual issue. Note that it was done in Spectator.

https://user-images.githubusercontent.com/89668531/222430798-df043037-0747-40ab-aec7-dd4daa0f253c.mp4

Here It went dormant, while I tried to see what happens if I go through different gamemodes.

https://user-images.githubusercontent.com/89668531/222430915-b3ec9b90-973e-4511-8163-6cd1201af297.mp4

And here I free the beast from what was causing it so much trouble.

**Comment by AzureDoom** [comment]
This is fixed in the newest patch!
