### ISSUE TITLE
Can't stack Spawn Egg from the Mod

### ISSUE THREAD

**Issue by WorldSpinAround** [cybercat-mods/gigeresque#131]
All other Spawn Eggs from the base Game can be stacked, it is especially obvious when you middle-click an egg in creative to get a full stack of it.
Since spawn eggs can not be obtainable in survival, there isn't an obvious reason why it wouldn't be stackable like other spawn eggs.

**Comment by AzureDoom** [comment]
This would be an issue with azurelib as it handles spawn eggs for all my mods, can you make an issue under that repo please?
