### ISSUE TITLE
[1.19.3] Ticking Entity Error

### ISSUE THREAD

**Issue by Dragonfly-Totem** [cybercat-mods/gigeresque#133]
**Bug**: Ticking Entity

**Mods**: There's several on the server itself, but it _appears_ to be an interaction between only Minecraft and Gigeresque.  At the moment, the major relevant ones to the Gigeresque stack are **Minecraft 1.19.3**, **Fabric API 0.75.1**, **AzureLib 1.0.4**, **Gigeresque 0.5.12**; Full list in the attached crashlog

**What is the Error?**
Full log attached.  Looks like an interaction between a minecraft:witch and a facehugger went very sideways.  Not entirely sure what happened there.

[crash-2023-03-04_21.04.24-server.txt](https://github.com/cybercat-mods/gigeresque/files/10890617/crash-2023-03-04_21.04.24-server.txt)

**Comment by LatentDesire1** [comment]
I'm experiencing the same issue it would seem. Looks like it's happening while the facehugger is on a villager.
https://paste.ee/p/CQxYA

**Comment by LatentDesire1** [comment]
Looks like updating the mods in a new instance fixed the issue. Looks like were were both using an out of date version of Azurelib.
