### ISSUE TITLE
Locate Structure command breaking world with Gigeresque structures as target

### ISSUE THREAD

**Issue by Zainyest** [cybercat-mods/gigeresque#141]
on latest 1.19.2 version gigeresque-1.19.2-0.5.15.jar

When using the locate command "/locate structure gigeresque:gig_dungeon" and the others I could find, the world would stop ticking and the client could still run around without loading new chunks, no mobs would move, etc. Regular commands and the locate command on anything else would still work without issue. No logs pertaining to server or problem after using the locate command in this manner. Really strange issue, my FPS even improved after running the command so something most likely stopped entirely.

log: (ran command at the bottom directly after "[System] [CHAT] The nearest #minecraft:mineshaft...")
[latest.log](https://github.com/cybercat-mods/gigeresque/files/10894877/latest.log)

**Comment by AzureDoom** [comment]
Depending on your system, it take take a few minutes for the locate command to work, this is a vanilla level issue due to the massive of the dungeon.

**Comment by Zainyest** [comment]
Ah, thanks for letting me know! I had no idea vanilla didn't handle big structures well.
