### ISSUE TITLE
Particle shown when Xenomorph Idle

### ISSUE THREAD

**Issue by WorldSpinAround** [cybercat-mods/gigeresque#143]
![image](https://user-images.githubusercontent.com/89668531/223418048-84e85a38-9c1f-485a-a214-36ec73c5802e.png)

I get this is slowness effect so he doesn't move, but... I think the true tag has been left aside here, to showcase particles.

**Comment by AzureDoom** [comment]
Was left in for debugging, everything seems to be fine now so removed with the newest patch.
