### ISSUE TITLE
HWG napalm grenade crash

### ISSUE THREAD

**Issue by barteknieznany** [cybercat-mods/gigeresque#147]
I was playing around with some mods and wanted to use the napalm grenade to get rid of some mobs. when i threw the grenade directly at a mob the grenade made a black effect cloud, game froze, and then crashed. here is the crash report:
[crash-2023-03-18_16.27.04-server.txt](https://github.com/cybercat-mods/gigeresque/files/11009247/crash-2023-03-18_16.27.04-server.txt) 
(i dont even know if this crash report will work anymore but if it wont then i can send the issue on discord)

**Comment by AzureDoom** [comment]
This issues tab is for Gigeresque crashes. HWG has it's Github.
