### ISSUE TITLE
Mobs ignore /team system

### ISSUE THREAD

**Issue by WorldSpinAround** [cybercat-mods/gigeresque#149]
Where any other mob in the game (including creeper and wither) ignore you if you and them are in the same team, every other mob of the mod simply do not care and will still attack you.

This makes creating datapacks hard to make, especially when you want to make it, so they don't attack a specific tagged mob for a complex purpose. Or even make (I saw someone mention it in the discord), an Origin, out of the Xenomorph.

I get the idea is "no xeno fanfiction", and of course this shouldn't be a thing in the base gameplay of the mod. But for technical work, the fact that they ignore several settings makes it hard to work with them.

**Comment by AzureDoom** [comment]
This is intended, as I have stripped the team checks from their AI code.

**Comment by WorldSpinAround** [comment]
Alright, nice, nice....
cool.
