### ISSUE TITLE
Egg still do not respect having {NoAI}

### ISSUE THREAD

**Issue by WorldSpinAround** [cybercat-mods/gigeresque#150]
In the latest build of both the main mod and the dependencies, I noticed summoning or editing the NBT of an Egg, so it could have its AI disabled (just like how when you disable the AI of any other creature, they don't do anything)...

Well, the Egg still acts as usual. Which renders some projects I have impossible.

**Comment by AzureDoom** [comment]
Make sure you are using `/summon gigeresque:egg ~ ~ ~ {NoAI:1}` as that works just fine 
![2023-03-25_20 39 44](https://user-images.githubusercontent.com/7415711/227749049-3678a649-08ca-428a-aa1c-a28d644e3ef1.png)
