### ISSUE TITLE
Egg Biomes?

### ISSUE THREAD

**Issue by xXGamerAwesomeXx** [cybercat-mods/gigeresque#154]
Hi. Since there's a question label I'm going to assume you can ask questions about the mod here... my question is what egg biomes (seen at the bottom of the config file) are. Is it like eggs can appear naturally in certain biomes? Alright question over bye bye :)

**Comment by AzureDoom** [comment]
Yes, what biomes you want to them to spawn in.

**Comment by xXGamerAwesomeXx** [comment]
Alright. But.. where would I find the names of biomes to put there? (Sorry if I shouldn't be talking here after its been closed as completed, I'm still a bit new to issues on github...)
EDIT: Nevermind found a source of names

**Comment by ImpulsiveLass** [comment]
Yeah it’s easiest to find it in game by typing in /locate biome and writing biomes exactly as shown i.e minecraft:plains

When putting it in the config you would list it as
          “minecraft:plains”,
          “minecraft:desert”,
          “minecraft:lush_caves”

**Comment by xXGamerAwesomeXx** [comment]
Okay I'll try minecraft: again... (Having some trouble figuring out how to type it, thanks for the help. :)

**Comment by xXGamerAwesomeXx** [comment]
I'm not finding any eggs... can someone look at this part of the file and check I've typed it correctly?
  ],
  "alienegg_biomes": [
    "minecraft:swamp",
    "minecraft:mangrove_swamp",
    "minecraft:river",
    "minecraft:frozen_river",
    "minecraft:beach",
    "minecraft:snowy_beach",
    "minecraft:stony_shore",
    "minecraft:warm_ocean",
    "minecraft:lukewarm_ocean",
    "minecraft:deep_lukewarm_ocean",
    "minecraft:ocean",
    "minecraft:deep_ocean",
    "minecraft:cold_ocean",
    "minecraft:deep_cold_ocean",
    "minecraft:frozen_ocean",
    "minecraft:deep_frozen_ocean",
  ],
  "alienegg_spawn_weight": 10,
  "alienegg_min_group": 1,
  "alienegg_max_group": 1
}

**Comment by xXGamerAwesomeXx** [comment]
Hang on, I've just realised the last biome (deep frozen ocean) is followed by a , but judging from the rest of the file, the end shouldn't a have a ,. I'll delete that and see if it helps.

**Comment by xXGamerAwesomeXx** [comment]
Still nothing. Guess all I can do is wait for some more help.

**Comment by Yucklets** [comment]
> Still nothing. Guess all I can do is wait for some more help.

If you want to see an increase of eggs you need to edit these values

"alienegg_spawn_weight": 10,
"alienegg_min_group": 1,
"alienegg_max_group": 1

as of now they have a very small chance of spawning only one egg in the biomes you chose.

**Comment by xXGamerAwesomeXx** [comment]
Ohhh okay. Could you explain the options? I've especially been wondering what a spawn weight is for a while...

**Comment by Yucklets** [comment]
> Ohhh okay. Could you explain the options? I've especially been wondering what a spawn weight is for a while...

alienegg_spawn_weight, the higher the number here, the more likely to randomly choose to spawn this
alienegg_min_group, the minimum amount of eggs that can be spawned when it's chosen
alienegg_max_group, the maximum amount of eggs that can be spawned when it's chosen

**Comment by xXGamerAwesomeXx** [comment]
Is there a maximum number for the spawn weight? Feels like there would be for a chance thing...
Also, would raising the max cause them to spawn in eachother or does it automatically spread them?

**Comment by ImpulsiveLass** [comment]
I don't know if there is a maximum, 1 is high enough in my opinion, the eggs are spread out automatically but more than 1 at a time and with a higher spawn weight causes them to be everywhere since they don't despawn like zombies or creepers do.

**Comment by xXGamerAwesomeXx** [comment]
Okay, that should be everything.  Thanks everyone!
