### ISSUE TITLE
Strange eggmorphing placement

### ISSUE THREAD

**Issue by FakeACat** [cybercat-mods/gigeresque#156]
Minecraft 1.19.4, Gigeresque 0.5.26
I think the screenshot describes this best, aliens sometimes place mobs they are eggmorphing several blocks above the ground
This is fairly easy to replicate, it seems to happen when the nest resin block they want to go to is also above the ground (like on a cave wall or hill)
![image](https://user-images.githubusercontent.com/33098659/235473246-85fc88b9-c7e3-4b95-abf3-226fba22a55e.png)

**Comment by AzureDoom** [comment]
This is currently intended as it's just the xeno placing resin and placing the entity in it's nest.
