### ISSUE TITLE
Egg spawn glitch

### ISSUE THREAD

**Issue by Niconoko** [cybercat-mods/gigeresque#158]
Minecraft: 1.19.2
Azure Lib v1.0.18
Gigeresque v0.5.29
Smart Brain Lib v1.9

- Using alien egg spawn onto any floor cause it to glitch into the ground and lag the game.
- Possibly give a massive lag when tp tothe dungeon location.

![AL02](https://github.com/cybercat-mods/gigeresque/assets/24541618/70704b8e-c5d6-4ecf-8396-52cdd5a3bbe9)

**Comment by AzureDoom** [comment]
Thanks, this is fixed now!
