### ISSUE TITLE
Aliens can't leave through the holes they break

### ISSUE THREAD

**Issue by TheCronockian** [cybercat-mods/gigeresque#160]
It seems that the aliens have the ability to break some types of blocks to head towards entities, however the hole they break is only 2 blocks high. I tested it a bit and it seems that the adult aliens require a 3x1 space to move through, meaning they can't get through the holes they break. I'm using version 0.5.29 for reference.

**Comment by ImpulsiveLass** [comment]
Im not sure of the specifics but I know they both break blocks directly and place acid purposely  to melt blocks. Blocks they can break directly and melt with acid have separate lists so the block involved is important. From my testing they typically make at least 3 block tall holes but I have played the most recent build.

**Comment by TheCronockian** [comment]
As far as I was aware 0.5.29 is the most recent build. This is what I'm seeing happen. They break the upper two blocks but leave the bottom of the stack of 3 there, causing the issue where they can't escape/break into things. I know they are suppose to have a crawl animation but I don't know if that is allows them to go through 2 high spaces. In my testing this is causing them to get stuck inside/outside when there are entities they would otherwise attack nearby.
![2023-05-30_11 17 51](https://github.com/cybercat-mods/gigeresque/assets/135042345/cc6d4635-72ad-4aba-ac6f-7d5a7c75c87f)
