### ISSUE TITLE
[Feature Request] Restrict dimensions/ AdAstra compat

### ISSUE THREAD

**Issue by gittibene** [cybercat-mods/gigeresque#162]
Love the mod, would it be possible to restrict them from spawning/generating in the overworld and have the structures only generate on Ad Astras Glacio for example?

**Comment by AzureDoom** [comment]
You can do this via a datapack by changing this json here https://github.com/cybercat-mods/gigeresque/blob/1.19/src/main/resources/data/gigeresque/tags/worldgen/biome/has_structure/gig_dungeon_biomes.json which be defaults chooses mountains

**Comment by gittibene** [comment]
Great, thank you!
