### ISSUE TITLE
Replace java.awt usage

### ISSUE THREAD

**Issue by vanchaxy** [cybercat-mods/gigeresque#163]
Can we replace java.awt.color with Android-friendly alternative? That will allow to use this mod with QuestCraft.

**Comment by AzureDoom** [comment]
This is an issue for AzureLib.

**Comment by vanchaxy** [comment]
It is not.

https://github.com/cybercat-mods/gigeresque/blob/ffc6781d17957f27286975a819586cd48d47265f/src/main/java/mods/cybercat/gigeresque/common/status/effect/impl/DNAStatusEffect.java#L3
https://github.com/cybercat-mods/gigeresque/blob/ffc6781d17957f27286975a819586cd48d47265f/src/main/java/mods/cybercat/gigeresque/common/status/effect/impl/AcidStatusEffect.java#L3
https://github.com/cybercat-mods/gigeresque/blob/ffc6781d17957f27286975a819586cd48d47265f/src/main/java/mods/cybercat/gigeresque/common/status/effect/impl/TraumaStatusEffect.java#L3
https://github.com/cybercat-mods/gigeresque/blob/ffc6781d17957f27286975a819586cd48d47265f/src/main/java/mods/cybercat/gigeresque/common/status/effect/impl/SporeStatusEffect.java#L3

**Comment by AzureDoom** [comment]
Yes but that Color replacement will be done by AzureLib, not this mod.
