### ISSUE TITLE
Game crashing with Xeno egg

### ISSUE THREAD

**Issue by CaitTheHusky** [cybercat-mods/gigeresque#164]
For some reason my game keeps crashing whenever the Xenomorph egg tries to open whenever the egg ticks it crashes the game and then perma locks that world is there a way i can fix that?

**Comment by AzureDoom** [comment]
Make sure you are fully up-to-date (if on 1.20, update to 1.20.1)

**Comment by CaitTheHusky** [comment]
Ill give it a try and see if it works

**Comment by CaitTheHusky** [comment]
it worked thank you very it was my Minecraft version i was playing on 1.20 i can play with mod now.
