### ISSUE TITLE
Ad Astra optional dependency?

### ISSUE THREAD

**Issue by xXGamerAwesomeXx** [cybercat-mods/gigeresque#169]
Hey, I'm back. Once again, I'm hoping the question tag means I can ask this here. So...

How does Gigeresque interact with Ad Astra? Do facehugger eggs appear on the other planets or something? I had a little look around Ad Astra's github but I couldn't really see anything mentioning Gigeresque or egg biomes...

**Comment by ImpulsiveLass** [comment]
Not an issue, xenos don't need to breathe in space.

**Comment by AzureDoom** [comment]
It's to auto tag xenos to breathe in space and on the planets
