### ISSUE TITLE
Crash after spawning an Alien Egg

### ISSUE THREAD

**Issue by LReaper31** [cybercat-mods/gigeresque#170]
Hi, I was in spectator searching if your structures were spawning (couldnt find any) I tried to spawn in creative some of your creatures, huggers and chest alien, working.

I spawn an Alien egg and not sure if when it spawned or if by right clicking it, made me crash instantly plus no more able to load the map.

Minecraft launcher error : The game crashed whilst ticking entity
Error: java.lang.IllegalStateException: Unregistered memory fetched: minecraft:walk_target

here a crash log : https://pastebin.com/5z1wsmWB

**Comment by AzureDoom** [comment]
Use 1.20.1 and update.

**Comment by LReaper31** [comment]
The whole server is on 1.20 I wont pass to 1.20.1 and miss half of my ressource pack.

Is there a possibility you do a last update or correction please ?

**Comment by AzureDoom** [comment]
No, I only support the latest MC version.

**Comment by LReaper31** [comment]
Well, thanks for let us knows
