### ISSUE TITLE
How do I launch this???

### ISSUE THREAD

**Issue by xXGamerAwesomeXx** [cybercat-mods/gigeresque#173]

**Comment by xXGamerAwesomeXx** [comment]
no wait why did it post already???? ok wait for me to type the rest of this

**Comment by xXGamerAwesomeXx** [comment]
Smartbrainlib seems to not exist for quilt 1.20.1
I am playing Gigeresque on quilt 1.20.1
Gigeresque has smartbrainlib as a required dependency
Help

**Comment by AzureDoom** [comment]
Use the Fabric version of mods on Quilt to use everything.
