### ISSUE TITLE
Face hugger latching is broken/takes forever yet again

### ISSUE THREAD

**Issue by Ragabagayaga** [cybercat-mods/gigeresque#174]

**Comment by AzureDoom** [comment]
The timer is based on your configs; default is 4 minutes.

**Comment by Ragabagayaga** [comment]
Sorry I did not mean by time I knew that I meant by how long it takes them to latch onto somebody's face as they will run around them and bump into them but not latch until the perfect hitboxes collide.

**Comment by AzureDoom** [comment]
If you are blocking at all, this can cause this as they can be stopped from latching by blocking.

**Comment by Ragabagayaga** [comment]
No it does it with a villager I am trying to get a video right now.

**Comment by Ragabagayaga** [comment]
https://github.com/cybercat-mods/gigeresque/assets/104508340/c9dd32cd-2765-4089-8645-36c5a5a37db7

**Comment by Ragabagayaga** [comment]
On the second villager you can see the facehugger trying to latch but unable to.
