### ISSUE TITLE
Skin layer, armor, equipped shield not rendering 1.20.1

### ISSUE THREAD

**Issue by ykvox** [cybercat-mods/gigeresque#177]
Using qfapi-7.2.0_qsl-6.1.1_fapi-0.88.0_mc-1.20.1

As said in the title, there are issues, equipped items in offhand are invisible as well as some armor pieces, skin layers and even custom pumpkin models

**Comment by ImpulsiveLass** [comment]
This is specifically with Gigeresque?

**Comment by ykvox** [comment]
yep, extensively went through the modlist to find out

i am going to check if gigeresque is causing this on it's own though

**Comment by AzureDoom** [comment]
Please ensure your AzureLib is fully updated as well.

**Comment by ykvox** [comment]
all good !
didn't checked this update
_v1.0.27
Fixes Armor render bug with Iris_

thank you very much for the lightning-fast response !

**Comment by AzureDoom** [comment]
Please note that bug was only for Azurelib Armors, not vanilla/other modded armors.

**Comment by ykvox** [comment]
well it fixed all of the issues mentioned before :)

**Comment by ykvox** [comment]
well, back again, sorry to bother

after a little digging i found the conflicting mods
the mentionned mods are all up to their latest version

Gigeresque combined with any cape or skin restorer will cause the outer skin layer and cape to dissapear

![image](https://github.com/cybercat-mods/gigeresque/assets/61479000/ee37b47e-17d8-4a16-8220-7f7107750384)

The Azurelib fix worked when i was playing in solo since it is authenticated with mojang, but not on my server which is running in offline mode and needs those skin mods

the tried mods are:
-Kappa
-Capes
-SkinRestorer
-FabricTailor

again, sorry i didn't test this further earlier, i hope you have an idea where the issue is coming from

thank you in advance !

**Comment by AzureDoom** [comment]
Sorry, I don't provide support for offline/cracked servers.
