### ISSUE TITLE
carry checks

### ISSUE THREAD

**Issue by ImpulsiveLass** [cybercat-mods/gigeresque#179]
https://streamable.com/jmahl0

Xenos act kinda silly with carrying, good bit of spinning, slapping, breaking lights, dropping mobs in weird wrong spots, dropping acid, etc

**Comment by ImpulsiveLass** [comment]
This was in the most recent fabric with the most recent azurelib and sbl*

**Comment by AzureDoom** [comment]
Should be tweaked now in v0.5.40!
