### ISSUE TITLE
Facehuggers cannot latch to mobs that are on the edges of resin

### ISSUE THREAD

**Issue by ImpulsiveLass** [cybercat-mods/gigeresque#181]
https://streamable.com/9ioqz2

**Comment by AzureDoom** [comment]
This is normal, as the mob is considered eggmorphing (you can see the particles) as they are touching the cross-block. However, it shouldn't be targeting it either, which it is.

**Comment by ImpulsiveLass** [comment]
The dude would be deeper in and completely frozen right? I believed it to not be in stasis as they turn their head and whole body as I move around

**Comment by AzureDoom** [comment]
Nah, just touching the block itself is enough to apply the egg morph status.
