### ISSUE TITLE
Carry issue 0.5.41

### ISSUE THREAD

**Issue by ImpulsiveLass** [cybercat-mods/gigeresque#182]
https://streamable.com/w4vhgw

Xenos are still a bit silly and often misplace mobs they want to eggmorph/put them down randomly sometimes through walls. They always seem to drop what they are carrying if they want to smack or melt out an obstruction etc

**Comment by AzureDoom** [comment]
Is this still an issue in recent versions btw?

**Comment by AzureDoom** [comment]
Closing as I haven't gotten any feedback regarding the latest updates.
