### ISSUE TITLE
Ad Astra compatibility breaks eggs and face huggers

### ISSUE THREAD

**Issue by Axxand** [cybercat-mods/gigeresque#184]
When using Ad Astra now even just installing the mod causes face huggers and eggs to just not work at all

**Comment by Axxand** [comment]
managed to fix this bug by removing the entity_types folder in the Ad Astra data pack, will update if I can figure out what's bugging it in there.

**Comment by AzureDoom** [comment]
Thanks, I will take a look to fix it soon!
