### ISSUE TITLE
face huggers not attacking Martian Raptors

### ISSUE THREAD

**Issue by Axxand** [cybercat-mods/gigeresque#189]
Don't know if this is a bug due to face huggers only facing one direction but they seem to be able to attack things just fine but Martian raptors they just move them not seeming to be able to attack, think this just has something to do with the Martian raptor hitbox.

**Comment by AzureDoom** [comment]
Looking at the code of the Raptors, looks like they are considered undead so they will be removed from the tag. https://github.com/terrarium-earth/Ad-Astra/blob/1.20.x/common/src/main/java/earth/terrarium/ad_astra/common/entity/mob/MartianRaptor.java#L46
