### ISSUE TITLE
Black goo spawns way too many stalkers

### ISSUE THREAD

**Issue by Axxand** [cybercat-mods/gigeresque#194]
Don't know if its meant to be like that but when you die to the black goo blood it spawns like 10 stalkers instead of one

**Comment by Axxand** [comment]
does the same for any small animal too it will just spawn a lot

**Comment by AzureDoom** [comment]
The fluid itself or the blood that drops from the mutants?

**Comment by Axxand** [comment]
drops from the mutants

**Comment by Axxand** [comment]
it seems to think the dead body thats left after anything dies is a entity it can take so it just keeps making them until it goes away
