### ISSUE TITLE
multiple mobs can be eggmorphed in the same web

### ISSUE THREAD

**Issue by ImpulsiveLass** [cybercat-mods/gigeresque#195]
https://streamable.com/8d9y91

**Comment by AzureDoom** [comment]
Yeah, there is no easy fix for this since there isn't a neat way to test if there is already an entity in the block. This will be left as is for sometime until a later date.

**Comment by LatentDesire1** [comment]
Think I'll try adding that mod that makes mobs solid. Maybe that would be a temp fix for this? Can't have multiple in the same block if you can't occupy the same space. lol
