### ISSUE TITLE
NYF's spiders crash.

### ISSUE THREAD

**Issue by llkiur** [cybercat-mods/gigeresque#197]
Crashes when gigeresque-1.20.1-0.5.50 fabric and nyfsspiders-fabric-1.20.1-2.1.1.jar are installed.

**Comment by AzureDoom** [comment]
Likely a mixin conflict due to the stripped-down version we use, got a crash log exactly?

**Comment by llkiur** [comment]
[latest.log](https://github.com/cybercat-mods/gigeresque/files/12659352/latest.log)

**Comment by AzureDoom** [comment]
This is an issue with the new library I made that is a stripped down version of Nys Spiders, which I have fixed in this https://github.com/AzureDoom/Better-Crawling-ML/commit/5d9fe705bcbc617f437a4a96c578b5c64cbd92fd which will be bundled with the next Gigeresque release!

**Comment by llkiur** [comment]
Ahhh, good to know ty, looking forward to it.
