### ISSUE TITLE
Default Xeno bending its head weirdly

### ISSUE THREAD

**Issue by VeryKitty03** [cybercat-mods/gigeresque#199]
![2023-09-26_20 20 47](https://github.com/cybercat-mods/gigeresque/assets/104660514/4d44496f-7574-4917-9faa-c1d56e580928)
Is this normal?
another picture
![2023-09-26_20 37 51](https://github.com/cybercat-mods/gigeresque/assets/104660514/a8154039-2202-4c6b-8cb5-f8ab2a7047b3)

**Comment by AzureDoom** [comment]
What mod version and mc version?

**Comment by VeryKitty03** [comment]
The mod version is 0.5.53 and the game version is 1.20.1
