### ISSUE TITLE
They on the pill

### ISSUE THREAD

**Issue by ImpulsiveLass** [cybercat-mods/gigeresque#200]
Gregnation ends with mobs bleeding nonstop (no bursting). (Ignore the huggers being wack they are fine with standard config, I just sped it up to show the whole process in a shorter clip)

https://streamable.com/q5cqk3

**Comment by AzureDoom** [comment]
What are your config values?

**Comment by ImpulsiveLass** [comment]
Iirc I had the Impreg and falling off both at a quarter or third of the time, like 360 each? I think 1200 on both is default
