### ISSUE TITLE
skin issue

### ISSUE THREAD

**Issue by ykvox** [cybercat-mods/gigeresque#202]
hello again !
regarding this issue
https://github.com/cybercat-mods/gigeresque/issues/177

i've found TheDeathlyCow's Frostiful was facing the same and fixed it, i know you don't wish to provide help for offline servers but if you'd like to have a look by any chance, i'll leave it here:
https://github.com/TheDeathlyCow/frostiful/issues/50

i wish you a good day
vox

**Comment by AzureDoom** [comment]
Support will never be given for cracked versions.
