### ISSUE TITLE
This is not an issue, but a question. I apologise for putting it here but I did not know where else to. What is the Gigeresque connector on CurseForge? I saw that it is for Forge version but you have said that you will never do a Forge port

### ISSUE THREAD

**Issue by sonofabaconator** [cybercat-mods/gigeresque#203]

**Comment by ImpulsiveLass** [comment]
Sinytra connector, it+fortified fabric api allows you to run fabric mods on forge, for Giger you will use the fabric azurelib and forge smartbrainlib iirc

**Comment by sonofabaconator** [comment]
so... your saying i can have xenos on my forge modded worlds???? dude you have no idea how ecstatic this makes me

**Comment by sonofabaconator** [comment]
so i put the connector as well as the fabric mod or is the mod already in the connector?

**Comment by AzureDoom** [comment]
Yes, you can use connector and it's API with Gig. Please note you will be able to use either the Forge and Fabric AzureLib and SmartBrainLib with it now as those issues are resolved.
