### ISSUE TITLE
Crash Log. Something to do with Facehuggers.

### ISSUE THREAD

**Issue by LatentDesire1** [cybercat-mods/gigeresque#204]
https://paste.ee/p/FVAz5

**Comment by Ryuco** [comment]
This also happens with the mutant stalker sometimes when you use projectiles to kill it.

**Comment by AzureDoom** [comment]
> This also happens with the mutant stalker sometimes when you use projectiles to kill it.

would need a crash log for that but for that, please create a new issue.
