### ISSUE TITLE
Model Alignment

### ISSUE THREAD

**Issue by LatentDesire1** [cybercat-mods/gigeresque#205]
The two layers of freshly adult xenos aren't meshing up while crawling a good amount of the time. Would see one of the xeno being regular black and another of the pale xeno jutting out at different angles.

**Comment by AzureDoom** [comment]
Are you using shaders @LatentDesire1?

**Comment by Ragabagayaga** [comment]
> The two layers of freshly adult xenos aren't meshing up while crawling a good amount of the time. Would see one of the xeno being regular black and another of the pale

He is most likely not because I am having the same issues with only gigeresque, hwg, and its requirements.
