### ISSUE TITLE
Facehugger crash issue 

### ISSUE THREAD

**Issue by Ragabagayaga** [cybercat-mods/gigeresque#206]
The facehugger will facehug something then if shot or killed in any way it will crash the game, Iron swords do not detach the facehugger anymore so I believe it has something to do with the detaching mechanic and if the player dies I believe it also crashes the game. Also a suggestion for nests: make them a little bit more easy to traverse through and not as annoying because if you touch a single piece of hive resin it encases you and begins to eggmorph you making it more annoying than terrifying.

**Comment by ImpulsiveLass** [comment]
If the resin didn’t center mobs then xenos wouldn’t be able to eggmorph mobs and players, instead you should not walk into cross resin, you wouldn’t walk right into lava would you?

**Comment by AzureDoom** [comment]
No crash log, invalid bug report.

**Comment by Ragabagayaga** [comment]
> If the resin didn’t center mobs then xenos wouldn’t be able to eggmorph mobs and players, instead you should not walk into cross resin, you wouldn’t walk right into lava would you?

I mean like it shouldnt create as much resin

**Comment by AzureDoom** [comment]
The resin was increased by demand of others and will not be lowered at this time.
