### ISSUE TITLE
Head Bending Weirdly... Again

### ISSUE THREAD

**Issue by VeryKitty03** [cybercat-mods/gigeresque#211]
![image](https://github.com/cybercat-mods/gigeresque/assets/104660514/4afcc48a-456c-4aaf-8fa0-7427ed2948ca)
The head movement on aliens is broken again in mod version 1.9.7.  The game version is 1.20.1.

**Comment by AzureDoom** [comment]
Already fixed in dev, so closing for now.

**Comment by VeryKitty03** [comment]
k
