### ISSUE TITLE
Alex’s caves not working with gigersque

### ISSUE THREAD

**Issue by NexXic66** [cybercat-mods/gigeresque#213]
Hello, 

I saw that the newest version of gigeresque added compat Alex’s caves. It says via data pack on the changelog, but I cannot seem to find the data pack anywhere, or is it something thats already built in with v.0.5.58? If it is built in with the version, my game saying exit code 1 whenever I start it up so im a little confuzled and I was wondering if I may get some assistance please?

**Comment by ImpulsiveLass** [comment]
1. Are you using the sinytra connector, forgified fabric api, and forge 47.1.3?
2. The datapack is not separate, it is automatically added to gig when it detects the mod.
3. I made the datapack, it simply allows certain mobs to be hosts (i.e. underzealots, vallumraptors, deeps ones) and blacklists certain mobs from being carried and headbit by xenos such as the tremorsaurus and forsaken

**Comment by NexXic66** [comment]
Oh i see, and yeah gigeresque mod is working fine by itself on forge, however the moment i added Alex’s caves it gives an error. I did have an extremely hard to time with having giger work on forge at first so maybe i did it wrong. 


When I boot the game up with just the gig mod, it says theres 50 mods downloaded but i only have 5 actually in the folder. There is a mini folder inside the mods folder titled. “Connector” which what looks like repeated .jar files of [gigersque better crawling, mapped srg] and and “azurelib fabric”. Idk if thats supposed to be there or if i should delete the duplicates but so far its been untouched.

**Comment by NexXic66** [comment]
Also forgot to mention there another file in the connector file called “temp” which is the same repeated jar files or Gigeresque better crawling and gigeresque connector azurelib and gigeresque connecter better crawiling”

**Comment by AzureDoom** [comment]
Those files are fine. A log will required for proper help.

**Comment by AzureDoom** [comment]
No update on this so closing
