### ISSUE TITLE
Config broke even after deletion.

### ISSUE THREAD

**Issue by Ragabagayaga** [cybercat-mods/gigeresque#214]
The config in the newest update makes facehuggers take like 30 seconds then detatch and the host will instantly burst. Even after I delete the config it still regenerates the config with the same thing just without my own extra settings. I have tried the completely default config and it still does this.

**Comment by AzureDoom** [comment]
Yes, the timers were lowered recently. Are you trying to extend them?

**Comment by Ragabagayaga** [comment]
> Yes, the timers were lowered recently. Are you trying to extend them?

No but are they supposed to be super short? I am just making sure its not a bug.

**Comment by AzureDoom** [comment]
Yes, they were lowered here: https://github.com/cybercat-mods/gigeresque/commit/b7522fa4bc3660f1c4d201cbd8f05611c78b1804
