### ISSUE TITLE
Runnerbursters maturing incorrectly

### ISSUE THREAD

**Issue by Yucklets** [cybercat-mods/gigeresque#215]
Runnerbursters growing up into Classic Aliens.

Tested on a fresh install of MC with just this mod and its requirements installed. Runnerbursters will always grow into Classic Aliens no matter how it was spawned, naturally or through a spawn egg. Pretty easily re-created, just watch a Runnerburster as it grows.

**Comment by sonofabaconator** [comment]
Yeah this happened to me before. I reported the bug, but when I tried to
test it they grew into runners every time (they wanted me to look dumb I
guess XD)
