### ISSUE TITLE
All xenox (adults, huggers etc) don't interested in mobs

### ISSUE THREAD

**Issue by xor360** [cybercat-mods/gigeresque#219]
Hi, new here. 
I have the newest Gigeresque mod (forge). In this update I've found that all xenos don't attack mobs and also me.
Huggers jump out of eggs and thats all... no life cycle. Adults (spawned) just stay in place or walk around.
Cheers,
Marcin

**Comment by AzureDoom** [comment]
Please ensure you are on 47.1.3 for Forge and the Neo version of SmartBrainLib, not the normal Forge version. Forge broken brains in versions past 47.1.3 and no support will be given for the higher versions.
