### ISSUE TITLE
Runner unable to crawl

### ISSUE THREAD

**Issue by SwiftSniffer** [cybercat-mods/gigeresque#227]
Either due to the lack of crawl mode, or because the Runner's hitbox is too tall, it can not follow a player in a hole:

![image](https://github.com/cybercat-mods/gigeresque/assets/137426407/0d37515b-7e2b-4965-a472-c68d06533a3c)

**Comment by AzureDoom** [comment]
Vent crawling is not implemented at this time. Will be added after current issues with classic are resolved
