### ISSUE TITLE
Alien will randomly be unable to pathfind across terrain

### ISSUE THREAD

**Issue by SwiftSniffer** [cybercat-mods/gigeresque#229]
For the sake of example:
![image](https://github.com/cybercat-mods/gigeresque/assets/137426407/8ea5addd-c44a-4a96-994b-124907fae9d4)
-In red is where the Alien successfuly walked across.
-Where it is now, it is stuck, wiggling on the spot, trying to climb the block.
-However, a few seconds later, it decided to climb on the block in yellow, and successfully.

It's an unstable behavior, however it happens so often enough that it inder the alien's movements when making a nest or when chasing mobs.

**What more, the alien's behavior is ALWAYS to be on the run, as if it detect an invisible prey.**

**Comment by CKuxixxWasTakenSomehow** [comment]
same

**Comment by Syclusion** [comment]
Use the previous versions of smartbrainlib 1.12 and gigeresque 5.61, pathfinding and overral ai is like.... so much better. The newest update broke so much, they can't pathfind over slabs crashing on forge etc etc

**Comment by CKuxixxWasTakenSomehow** [comment]
> Use the previous versions of smartbrainlib 1.12 and gigeresque 5.61, pathfinding and overral ai is like.... so much better. The newest update broke so much, they can't pathfind over slabs crashing on forge etc etc

it is now playable thank you
