### ISSUE TITLE
Facehuggers target and attach to Creepers (Alpha 38)

### ISSUE THREAD

**Issue by FakeACat** [cybercat-mods/gigeresque#23]
![2022-04-26_17 13 47](https://user-images.githubusercontent.com/33098659/165346161-82dc9738-cb3b-4f7a-8590-3519d360cebb.png)

**Comment by AzureDoom** [comment]
Can't reproduce, please check config.

**Comment by FakeACat** [comment]
It seems my config was outdated, deleting it and letting it regenerate fixes the issue

**Comment by AzureDoom** [comment]
Perfect, figured that was the case as creepers should have been blacklisted there. Closing this since fixed!
