### ISSUE TITLE
1.20.1 Forge not working

### ISSUE THREAD

**Issue by Lemonwaterie** [cybercat-mods/gigeresque#230]
This may sound odd, but whenever I Install forge 1.20.1 for this mod it doesn't seem to be read by the forge loader. Every other mod I installed works but this one. And I'm quite confused since it seems to be fine for everyone else. 
![Screneshot 1](https://github.com/cybercat-mods/gigeresque/assets/117230291/7b8f6b5b-8c37-4eca-b1f2-e5c21c5e79e2)
![Screenshot 2](https://github.com/cybercat-mods/gigeresque/assets/117230291/262e1429-36b8-4d4f-9402-1071704f6137)

If you need any more information let me know

Even after adding the two required mods to make it run the mod still isn't being read. I find it quite strange and i have not encountered this issue in years.

**Comment by Lemonwaterie** [comment]
Update, I discovered another part of it. The mod isn't creating a config file for it.
![Config](https://github.com/cybercat-mods/gigeresque/assets/117230291/8d210bef-651a-4a39-99aa-a08dc32f8433)
If it was working it would create a config. I am quite confused because I've used multiple versions of forge + I have also used multiple versions of the forge version of the mod.

**Comment by AzureDoom** [comment]
Please read through the dependencies properly
