### ISSUE TITLE
Question 1.19.2 Forge Port 🔥

### ISSUE THREAD

**Issue by Krimatoria** [cybercat-mods/gigeresque#231]
I would like to know if 1.19.2 Forge is planned. There are simply no more xenomorph mods for this version, and the only option for joining from Factories is the [Sinatra Connector](https://github.com/Sinytra/Connector/issues/121), but it is not planned for 1.19.2.

Therefore, only if there is a 1.19.2 Forge port. Yes, there is a 1.20.1 version, which is fine. It's just that some modpacks are difficult to adapt to new versions until some mods update mods. 

I just hope there might still be a port. The models are too cool and it would complement so many worlds in different modpacks or regular builds. Just a fan of the alien universe 

> Anyway, thanks for such a cool mod)

**Comment by AzureDoom** [comment]
A forge port is not happening and will not happen as this mods license.
