### ISSUE TITLE
SoundEngine

### ISSUE THREAD

**Issue by Krimatoria** [cybercat-mods/gigeresque#233]
gigeresque-connector-1.20.1-0.5.62.jar

> [01:43:39] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: gigeresque:alien_hiss
> [01:43:39] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: gigeresque:alien_ambient
> [01:43:39] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: gigeresque:alien_hurt
> [01:43:39] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: gigeresque:alien_death
> [01:43:39] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: gigeresque:alien_death_thud
> [01:43:39] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: gigeresque:alien_claw
> [01:43:39] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: gigeresque:alien_tail
> [01:43:39] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: gigeresque:alien_headbite
> [01:43:39] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: gigeresque:alien_crunch
> [01:43:39] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: gigeresque:alien_footstep
> [01:43:39] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: gigeresque:alien_handstep
> [01:43:39] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: gigeresque:egg_notice
> [01:43:39] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: gigeresque:egg_open
> [01:43:39] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: gigeresque:aqua_landmove
> [01:43:39] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: gigeresque:aqua_landclaw
> [01:43:39] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: gigeresque:burster_crawl
> [01:43:39] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: gigeresque:hugger_ambient
> [01:43:39] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: gigeresque:hugger_death
> [01:43:39] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: gigeresque:hugger_hurt
> [01:43:39] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: gigeresque:hugger_implant

**Comment by AzureDoom** [comment]
Please recreate using Fabric version. Connector bugs are not acceptable.
