### ISSUE TITLE
1.20.1 Forge 47.2.7 TPS Lag Need Optimization Aliens logic

### ISSUE THREAD

**Issue by Krimatoria** [cybercat-mods/gigeresque#234]
SmartBrainLib-forge-1.20.1-1.13.jar
gigeresque-connector-1.20.1-0.5.62.jar
Connector-1.0.0-beta.37+1.20.1.jar

The problem of constant TPS spikes causing server crashes and delays is caused by gigeresque:alien 

It can be seen from the reports that even the Skulk located nearby does not cause such falls. When removing all gigeresque:alien, it was this mob that caused the drop, the TPS was stabilized. Some individuals are in cages, which interferes with their logic of finding a way. They also get stuck in blocks. 

I also noticed a huge number of particles located inside the blocks, this is visible only in spectral mode. Although, as I thought earlier, this does not cause FPS or TPS to drop. 

I hope this information will be useful in future updates)

![image](https://github.com/cybercat-mods/gigeresque/assets/106809386/62266863-d245-4e1c-8af1-67995c4c3fd9)
![image](https://github.com/cybercat-mods/gigeresque/assets/106809386/1d5d043b-4170-475a-a187-48b3890d5cc1)

![2024-03-06_21 43 38](https://github.com/cybercat-mods/gigeresque/assets/106809386/585363ce-a6fa-4db7-b3b7-ed00746b666e)
![2024-03-06_21 43 22](https://github.com/cybercat-mods/gigeresque/assets/106809386/bac7ebed-f206-4df6-ad67-b789a1cba8f5)
![2024-03-07_21 45 44](https://github.com/cybercat-mods/gigeresque/assets/106809386/4442b5b2-d34d-4a96-9dae-a7965e14b3c1)
![2024-03-07_21 51 46](https://github.com/cybercat-mods/gigeresque/assets/106809386/3d21a2a6-99b6-4280-a87d-add2e9916f80)
![2024-03-07_21 54 16](https://github.com/cybercat-mods/gigeresque/assets/106809386/087c0861-9490-4609-bf0b-b5c322645121)
![2024-03-07_21 55 13](https://github.com/cybercat-mods/gigeresque/assets/106809386/7852f7b8-368f-48f1-9a20-213ae61e1dc8)
![2024-03-07_21 55 53](https://github.com/cybercat-mods/gigeresque/assets/106809386/b6cba478-1b92-4260-92b6-42896d358456)

**Comment by AzureDoom** [comment]
Please recreate in Fabric, Forge is on a "if it works, it works" case. All reports must be done tested in Fabric.

**Comment by Krimatoria** [comment]
> Пожалуйста, воссоздайте в Fabric, Forge работает по принципу «если работает, то работает». Все отчеты должны быть протестированы в Fabric.

I don't know if there will be time, but maybe I'll try. Unfortunately, I cannot port the entire assembly to Fabric.
