### ISSUE TITLE
Aquatic aliens can walk on water

### ISSUE THREAD

**Issue by Ragabagayaga** [cybercat-mods/gigeresque#242]
![aquaticalalienswalk](https://github.com/cybercat-mods/gigeresque/assets/104508340/b27eda96-a1a8-45e8-a79d-eb3bf22cf8ae)

**Comment by Ragabagayaga** [comment]
I believe this happens when a aquatic alien burster evolves in water but I am unsure.

**Comment by AzureDoom** [comment]
This is a weird quirk with Minecraft itself on this sadly.
