### ISSUE TITLE
Black fluid causes crashes

### ISSUE THREAD

**Issue by HellBr3ad** [cybercat-mods/gigeresque#247]
Edit: It's on Forge. Forgot to mention.
I have my own modpack, but according to crashlogs I am 99% sure that the black fluid from Gigeresque causes crashes. First, it basically destroyed a few of my test worlds. I must've rendered it in or something, because the world then became corrupted and unplayable. This happened like 3 or 4 times.
Now I cannot look through Mekanism's creative menu, because it sees a tank with black fluid and crashes. 

And small update from a second ago, I just took the black fluid bucket and when placed in the world it simply crashed the world and it is inaccessible anymore.
I also tried getting a fresh install with only Gigeresque and its dependencies (screenshots), but it doesn't even go into menu.
![image](https://github.com/cybercat-mods/gigeresque/assets/162746517/dd4cdbfa-23cb-4c7a-b33e-c3ae1213748d)
![image](https://github.com/cybercat-mods/gigeresque/assets/162746517/5bd05d1b-fb7b-4356-9cbb-522314ca4dbc)

[crash-2024-04-19_16.51.12-client.txt](https://github.com/cybercat-mods/gigeresque/files/15042080/crash-2024-04-19_16.51.12-client.txt)

[crash-2024-04-19_16.36.23-client.txt](https://github.com/cybercat-mods/gigeresque/files/15042085/crash-2024-04-19_16.36.23-client.txt)
[crash-2024-04-19_16.45.14-client.txt](https://github.com/cybercat-mods/gigeresque/files/15042086/crash-2024-04-19_16.45.14-client.txt)

I've attached 3 crash reports. The first one is from the clean MC with Gigeresque. The other two are from that modpack, one should be from when I put the black fluid on the ground and the other should be from looking at inventory.
Let me know if I should provide any more info :)

**Comment by AzureDoom** [comment]
Please test with Fabric, Forge logs are not valid for fixes.

**Comment by AzureDoom** [comment]
This is resolved for 0.5.71, aiming to release within the next day or two.

**Comment by HellBr3ad** [comment]
I was at the uni and didn't see that you commented. Glad you fixed it so quickly :) Thanks!
