### ISSUE TITLE
Game crashes upon startup

### ISSUE THREAD

**Issue by VeryKitty03** [cybercat-mods/gigeresque#258]
I am using gigeresque 1.20.1-0.5.70 with the latest version of fabric 1.20.1 and the game crashes when I try to start it.  I am using the required library mods.  Here is the crash report:
[crash-2024-04-19_13.49.54-client.txt](https://github.com/cybercat-mods/gigeresque/files/15045532/crash-2024-04-19_13.49.54-client.txt)

**Comment by AzureDoom** [comment]
This is fixed in dev and will be fixed in 0.5.71 when it releases within a few days.
