### ISSUE TITLE
Alien AI completely broken on 0.5.71

### ISSUE THREAD

**Issue by Ragabagayaga** [cybercat-mods/gigeresque#263]
Xenos can not climb up blocks properly, xenos go after their own acid made noises...

**Comment by Ragabagayaga** [comment]
![2024-04-20_11 10 50](https://github.com/cybercat-mods/gigeresque/assets/104508340/12ae55e4-0f91-47d8-baee-0dcb84f7f7fc)

**Comment by Ragabagayaga** [comment]
![2024-04-20_11 12 00](https://github.com/cybercat-mods/gigeresque/assets/104508340/0e8fda21-c4e2-45a0-890c-081e198144cd)

**Comment by AzureDoom** [comment]
This is being addressed in the next update of 1.20.4, no eta on release
