### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by derasell** [cybercat-mods/gigeresque#264]
1. Alien has become terribly slow, you can escape from him simply by walking.
2. This is probably obvious, but the alien constantly gets stuck somewhere and cannot find the way to the target. (also applies to other mobs from the mod)
3. if an alien is near the cross resin, he enters it and gets stuck there forever.
4. Chestburster and runnerbuster have sounds of taking damage like an full grown alien.
5. Facehuggers are too fast. besides, on the face of player they are slightly higher than they should be.
6. Chestburster begins to chase the player who hit him. (I think chestburster should try to run away from the player and other mobs).
7. Alien cannot bring a mob into the web and start egmorphing.
8. The animation of breaking through the skull when an alien grabs the target has disappeared.

**Comment by YOSHAAAAAfan** [comment]
thx for telling bro i only reported one issue, but this is so nice of you listing  all the issues. The result: we can play with more fun and joy.

**Comment by AzureDoom** [comment]
What version was this tested on?

**Comment by YOSHAAAAAfan** [comment]
i think its on the newest one. Because i was noticing the same issues in the newest version

**Comment by YOSHAAAAAfan** [comment]
I meant the 1.20.6 version, and those issues are also still in the 1.21 version,

**Comment by makumaku1974** [comment]
Using Surgical Kit kills me no chance of survival???

**Comment by makumaku1974** [comment]
Alien pathfinding is broken. Alien has a crawl animation but i think the alien cant figure how to pathfind neither crawl up to a player and decides to clip up the wall.

**Comment by makumaku1974** [comment]
I tested the latest version. Alien has gotten worse. Alien speed was improved but the animation is broken, pathfinding is broken, and sight is broken as well.

**Comment by AzureDoom** [comment]
These are all fixed in latest 1.21.1.
