### ISSUE TITLE
Ticking Entity crash when Warden is under the Acid effect

### ISSUE THREAD

**Issue by kd8lvt** [cybercat-mods/gigeresque#266]
When the Warden is under the Acid effect, it produces a ticking entity crash.

From the looks of it, it's receiving a null entity when trying to increase hostility? `isValidTarget` should handle that when following vanilla behaviour, from what I can tell, but for whatever reason the assertion in [WardenEntityMixin.java](https://github.com/cybercat-mods/gigeresque/blob/d20e9d4733c27c0ea4d4ec3da0688011246c78e6/src/main/java/mods/cybercat/gigeresque/mixins/common/entity/WardenEntityMixin.java) fails to prevent a crash in a production environment.

Edit: Here's a log, somehow I forgot to add that, woops. https://mclo.gs/E39ZcbK

**Comment by OwOday** [comment]
I have this same issue

**Comment by dedsec12345** [comment]
I have the same crash, its possible to disable acid?

**Comment by OwOday** [comment]
I patched it with this for the time being https://github.com/OwOday/fixmods

**Comment by OwOday** [comment]
its just a mixinsquared that stubs the broken mixin, incompatible with debugify

**Comment by dedsec12345** [comment]
> its just a mixinsquared that stubs the broken mixin, incompatible with debugify

how do you install it?

**Comment by AzureDoom** [comment]
Is fixed with the final 1.20.4 release, all new fixes will be only 1.20.6+

**Comment by OwOday** [comment]
Thanks for the info! I'm going to keep my pack on 1.20.1 with the rest of my mods though so I will continue to use my mixinsquared patch :P

> Is fixed with the final 1.20.4 release, all new fixes will be only 1.20.6+

**Comment by OwOday** [comment]
> > its just a mixinsquared that stubs the broken mixin, incompatible with debugify
> 
> how do you install it?

its a mod jar under releases on that github

**Comment by YaibaToKen** [comment]
> > > its just a mixinsquared that stubs the broken mixin, incompatible with debugify
> > 
> > 
> > how do you install it?
> 
> its a mod jar under releases on that github

Any chance you could point me towards the release with the patch mentioned?

**Comment by OwOday** [comment]
> > > > its just a mixinsquared that stubs the broken mixin, incompatible with debugify
> > > 
> > > 
> > > how do you install it?
> > 
> > 
> > its a mod jar under releases on that github
> 
> Any chance you could point me towards the release with the patch mentioned?

its the only one, its not a patched gigeresque, it patches it in runtime using mixinsquared, so you need both mods. https://github.com/OwOday/fixmods/releases/tag/main
