### ISSUE TITLE
Emeraldequipment and entiticulling - No data fixer registered

### ISSUE THREAD

**Issue by willbnu** [cybercat-mods/gigeresque#277]
1.21 - Fabric 

Any mod related to alien entities (like emeraldequipment, entityculling, etc.): They are showing "No data fixer registered" errors, which could affect functionality.

![image](https://github.com/user-attachments/assets/1656d823-ca9f-4177-a61f-1f7427c6dde5)

**Comment by AzureDoom** [comment]
Data fixers are mojang thing and not used by modders. This is a non issue
