### ISSUE TITLE
Acid damages boots in creative mode

### ISSUE THREAD

**Issue by mpustovoi** [cybercat-mods/gigeresque#278]
I don't think this is intentional behavior.
![image](https://github.com/user-attachments/assets/e2556a6f-a3f5-405e-abc0-ddd4f2d775ef)
![image](https://github.com/user-attachments/assets/104c427d-5377-43a0-b90b-aa77dfa4959a)
![image](https://github.com/user-attachments/assets/6e122cc8-3486-4d6b-9879-4dcd24921f11)
There are no errors in the logs.

**Comment by AzureDoom** [comment]
It's actually intended yes at this time https://github.com/cybercat-mods/gigeresque/blob/365bcb8bca5e56142c7830447b1cb522a931be7e/common/src/main/java/mods/cybercat/gigeresque/common/entity/impl/extra/AcidEntity.java#L113

**Comment by mpustovoi** [comment]
I mean, I agree that this is how it should be in survival mode.
However, in creative mode it's weird that boots take damage.

**Comment by AzureDoom** [comment]
As I had said, at this time. A configuration will be added in the next update to for this.
