### ISSUE TITLE
[Enhancement] Alien Enhancements.

### ISSUE THREAD

**Issue by makumaku1974** [cybercat-mods/gigeresque#279]
Alien Xenomorph should have a relative speeds and phases by adjusting it.

1. Alien is now fast in the latest update but not as fast enough where they run into the player in long distances. Basically they should do a dog running animation when chasing the player.

2. Alien should climb when players are 5 blocks tall to 10 blocks high, when higher than 10 blocks add the lunging attack when near player or jumping when the player runs.

3. Alien should crawl when block above them and a gap infront which is 1 block should be able to crawl to catch the player.
![image](https://github.com/user-attachments/assets/606d7c3e-6d89-4444-98a2-06c70ade4977)

4. Alien's tail attack should be more often but a tiny bit slow. If the player is out of reach by its main attack, the tail can reach out to attack the player within 3-4 blocks. 

5. Brain Burst attack animation needs to be fixed.

**Comment by AzureDoom** [comment]
Feel free to pr any changes but at this time ai is still basic and not finished

**Comment by makumaku1974** [comment]
will do in the next update.
