### ISSUE TITLE
Locate Command Long Response Time (Alpha 38)

### ISSUE THREAD

**Issue by Ragabagayaga** [cybercat-mods/gigeresque#28]

**Comment by AzureDoom** [comment]
Known, this due to custom code extending our structures 5x the Vanilla limit. Sadly not can be done without reducing the dungeons size.

**Comment by VeryKitty03** [comment]
do the structures still generate even though they can not be found with the command?

**Comment by Ragabagayaga** [comment]
> do the structures still generate even though they can not be found with the command?

Yes you can still find them use /locatebiome #gigeresque_has or whatever the entire command is and it will be around there but yet they do still generate.

**Comment by AzureDoom** [comment]
Correct the command works fine, we are just using a structure 5x the size of strongholds
