### ISSUE TITLE
Lots of Lag

### ISSUE THREAD

**Issue by TumbleElf** [cybercat-mods/gigeresque#283]
Using this version of the mod:
![image](https://github.com/user-attachments/assets/0f7abec5-5ad6-4a5e-aa77-01472d23d07e)

For some reason the Eggs cause a lot of lag, bringing me down 100 or so FPS. This happens in the dungeon areas. I know it is the eggs because once I delete them the lag goes away.

Any ideas on how to fix?

**Comment by AzureDoom** [comment]
1.20.1 is abandoned and this is fixed in 1.21
See spark for 1.21 where over 300 cause no tps lag
![image](https://github.com/user-attachments/assets/cf70041d-68fd-4fa2-b3e9-ec28403565bc)

**Comment by mpustovoi** [comment]
I don't know why, but AlienEggEntity's ticking takes up 30% of the server thread:
https://spark.lucko.me/2wXfmXFjXR (can't load an image for some reason).
