### ISSUE TITLE
Getting a weird crash.

### ISSUE THREAD

**Issue by supercid87** [cybercat-mods/gigeresque#286]
Crash is here

java.lang.IllegalStateException: Entity class mods.cybercat.gigeresque.common.entity.impl.classic.FacehuggerEntity has not defined synched data value 29
	at net.minecraft.class_2945$class_9222.method_56911(class_2945.java:231)
	at net.minecraft.class_1297.<init>(class_1297.java:310)
	at net.minecraft.class_1309.<init>(class_1309.java:270)
	at net.minecraft.class_1308.<init>(class_1308.java:148)
	at net.minecraft.class_1314.<init>(class_1314.java:17)
	at net.minecraft.class_1588.<init>(class_1588.java:31)
	at mods.cybercat.gigeresque.common.entity.AlienEntity.<init>(AlienEntity.java:102)
	at mods.azure.bettercrawling.CrawlerMonsterEntity.<init>(CrawlerMonsterEntity.java:129)
	at mods.cybercat.gigeresque.common.entity.impl.classic.FacehuggerEntity.<init>(FacehuggerEntity.java:91)
	at net.minecraft.class_1299.method_5883(class_1299.java:552)
	at mods.cybercat.gigeresque.common.entity.impl.classic.AlienEggEntity.method_5773(AlienEggEntity.java:204)
	at net.minecraft.class_3218.mixinextras$bridge$method_5773$214(class_3218.java)
	at net.minecraft.class_3218.wrapOperation$eoc001$porting_lib_entity$preEntityTick(class_3218.java:9807)
	at net.minecraft.class_3218.method_18762(class_3218.java:770)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

Prob Azure breaking stuff idk
Rest of the Log
 detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2945$class_9222.method_56911(class_2945.java:231)
	at net.minecraft.class_1297.<init>(class_1297.java:310)
	at net.minecraft.class_1309.<init>(class_1309.java:270)
	at net.minecraft.class_1308.<init>(class_1308.java:148)
	at net.minecraft.class_1314.<init>(class_1314.java:17)
	at net.minecraft.class_1588.<init>(class_1588.java:31)
	at mods.cybercat.gigeresque.common.entity.AlienEntity.<init>(AlienEntity.java:102)
	at mods.azure.bettercrawling.CrawlerMonsterEntity.<init>(CrawlerMonsterEntity.java:129)
	at mods.cybercat.gigeresque.common.entity.impl.classic.FacehuggerEntity.<init>(FacehuggerEntity.java:91)
	at net.minecraft.class_1299.method_5883(class_1299.java:552)
	at mods.cybercat.gigeresque.common.entity.impl.classic.AlienEggEntity.method_5773(AlienEggEntity.java:204)
	at net.minecraft.class_3218.mixinextras$bridge$method_5773$214(class_3218.java)
	at net.minecraft.class_3218.wrapOperation$eoc001$porting_lib_entity$preEntityTick(class_3218.java:9807)
	at net.minecraft.class_3218.method_18762(class_3218.java:770)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)

-- Entity being ticked --
Details:
	Entity Type: gigeresque:egg (mods.cybercat.gigeresque.common.entity.impl.classic.AlienEggEntity)
	Entity ID: 4932
	Entity Name: Alien Egg
	Entity's Exact location: -1993.50, -40.00, -8459.50
	Entity's Block location: World: (-1994,-40,-8460), Section: (at 6,8,4 in -125,-3,-529; chunk contains blocks -2000,-64,-8464 to -1985,319,-8449), Region: (-4,-17; contains chunks -128,-544 to -97,-513, blocks -2048,-64,-8704 to -1537,319,-8193)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Affected level --
Details:
	All players: 1 total; [class_3222['supercid87'/8, l='ServerLevel[New World]', x=-2034.05, y=-31.01, z=-8382.38]]
	Chunk stats: 4322
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,67,0), Section: (at 0,3,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 27657 game time, 27657 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Commands: true
	Level weather: Rain time: 45066 (now: false), thunder time: 45337 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 775
Stacktrace:
	at net.minecraft.class_3218.method_8538(class_3218.java:1693)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1024)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 4064067800 bytes (3875 MiB) / 9202302976 bytes (8776 MiB) up to 10569646080 bytes (10080 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i7-12700H
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.69
	Number of physical packages: 1
	Number of physical CPUs: 14
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 6144.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6094
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 34520.49
	Virtual memory used (MiB): 25196.74
	Swap memory total (MiB): 2048.00
	Swap memory used (MiB): 71.88
	Space in storage for jna.tmpdir (MiB): available: 715200.56, total: 952453.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 715200.56, total: 952453.00
	Space in storage for io.netty.native.workdir (MiB): available: 715200.56, total: 952453.00
	Space in storage for java.io.tmpdir (MiB): available: 715200.56, total: 952453.00
	Space in storage for workdir (MiB): available: 715200.56, total: 952453.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10080m -Xms256m
	Fabric Mods: 
		additionalstructures: Additional Structures 5.0.1-fabric
		advancednetherite: Advanced Netherite 2.1.6-1.21.1
		alternate-current: Alternate Current 1.9.0
		antixray: AntiXray 1.4.6
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		appleskin: AppleSkin 3.0.5+mc1.21
		architectury: Architectury 13.0.6
		astrocraft: Astrocraft 1.4.3+1.21.1
		audaki_cart_engine: Audaki Cart Engine 3.1.1
		azurelib: AzureLib 2.3.19
		badoptimizations: BadOptimizations 2.1.4
		balm-fabric: Balm 21.0.19
			kuma_api: KumaAPI 21.0.5-SNAPSHOT
		basicweapons: Basic Weapons 1.2.10+1.21
		beekeeperhut: Friends&Foes - Beekeeper Hut 2.0.1
		betterbeaconplacement: Better Beacon Placement 3.4
		betterconduitplacement: Better Conduit Placement 3.3
		bettermounthud: Better Mount HUD 1.2.4
		biomesoplenty: BiomesOPlenty 21.1.0.2
		bottleyourxp: Bottle Your Xp 3.4
		brickfurnace: Brick Furnace 1.21-4.1.1.0
		bronze: Bronze 1.0.10+1.21
		bucketlib: BucketLib 1.21-4.1.0.1
		caffeinated: Caffeinated 1.0.5
		camerautils: Camera Utils 1.21.1-1.0.16
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c6a
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a76a
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df3606a
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+565991296a
		ceramicbucket: Ceramic Bucket 1.21-6.1.1.0
		chalk: Chalk 2.2.5+1.21.1
			com_github_mclegoman_releasetypeutils: releasetypeutils 2.1.0
			fabric-simplelibs: Simple Fabric Libs 2.0.0
		chat_heads: Chat Heads 0.12.10
		chunksending: Chunksending Mod 1.21-2.8
		clientcrafting: clientcrafting Mod 1.21-1.8
		cloth-config: Cloth Config v15 15.0.130
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 19.0.0.1
		collective: Collective 7.84
		configurabledespawntimer: Configurable Despawn Timer 4.2
		connectivity: Connectivity Mod 1.21-5.7
		craftsaddles: Craft Saddles 1.0.1
		crawl: Crawl 0.13.0
		cupboard: cupboard 1.21-2.7
		despawningeggshatch: Despawning Eggs Hatch 4.4
		dismountentity: Dismount Entity 3.5
		distanthorizons: Distant Horizons 2.2.1-a
		doggytalents: Doggy Talents Next 1.18.29
		doubledoors: Double Doors 5.9
		dragondropselytra: Dragon Drops Elytra 3.4
		dragonfight: Dragonfight Mod 1.21-4.6
		dragonloot: DragonLoot 1.1.7
		dyed: Dyed 1.2.0
		edibles: Edibles 4.4
		elytra-hud: Elytra HUD 3.0.0
		emeraldequipment: Emerald Equipment 1.0.4
		enderitemod: Simple Enderite Mod 1.21-v1.5
		exlinecopperequipment: Copper Equipment 1.0.3
		explorerscompass: Explorer's Compass 1.21.1-2.2.5-fabric
		fabric-api: Fabric API 0.103.0+1.21.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bc19
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.21+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.6.1+9b16164119
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.28+1daea21519
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.18+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc92119
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.5+3fc0e55219
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209b19
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.17+1db1cc1f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabricloader: Fabric Loader 0.16.3
			mixinextras: MixinExtras 0.4.1
		fallingtrees: Panda's Falling Tree's 0.12.7
		farmersdelight: Farmer's Delight 1.21-2.1.8+refabricated
			mm: Manningham Mills 2.3
			porting_lib_base: Porting Lib Base 3.1.0-beta+fdrf.1+1.21
				porting_lib_accessors: Porting Lib Accessors 3.1.0-beta+fdrf.1+1.21
				porting_lib_asm: Porting Lib ASM 3.1.0-beta+fdrf.1+1.21
				porting_lib_attributes: Porting Lib Attributes 3.1.0-beta+fdrf.1+1.21
				porting_lib_blocks: Porting Lib Blocks 3.1.0-beta+fdrf.1+1.21
				porting_lib_common: Porting Lib Common 3.1.0-beta+fdrf.1+1.21
				porting_lib_entity: Porting Lib Entity 3.1.0-beta+fdrf.1+1.21
				porting_lib_extensions: Porting Lib Extensions 3.1.0-beta+fdrf.1+1.21
				porting_lib_fluids: Porting Lib Fluids 3.1.0-beta+fdrf.1+1.21
				porting_lib_gui_utils: Porting Lib Gui Utils 3.1.0-beta+fdrf.1+1.21
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 3.1.0-beta+fdrf.1+1.21
				porting_lib_tags: Porting Lib Tags 3.0
				porting_lib_transfer: Porting Lib Transfer 3.1.0-beta+fdrf.1+1.21
			porting_lib_config: Porting Lib Config 3.1.0-beta+fdrf.1+1.21
				porting_lib_core: Porting Lib Core 3.1.0-beta+fdrf.1+1.21
				porting_lib_gametest: Porting Lib GameTest 3.1.0-beta+fdrf.1+1.21
			porting_lib_item_abilities: Porting Lib Item Abilities 3.1.0-beta+fdrf.1+1.21
				porting_lib_level_events: Porting Lib Level Events 3.1.0-beta+fdrf.1+1.21
			porting_lib_lazy_registration: Porting Lib Lazy Register 3.1.0-beta+fdrf.1+1.21
			porting_lib_loot: Porting Lib Loot 3.1.0-beta+fdrf.1+1.21
				porting_lib_conditions: Porting Lib Conditions 3.1.0-beta+fdrf.1+1.21
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 3.1.0-beta+fdrf.1+1.21
		fastipping: Fast IP Ping 1.0.4
		ferritecore: FerriteCore 7.0.0
		fishontheline: Fish On The Line 3.4
		fixedanvilrepaircost: Fixed Anvil Repair Cost 3.4
		flamearrows: Fire arrows ignite fire 1.21.1-12-fabric
		followersteleporttoo: Followers Teleport Too 2.6
		forgeconfigapiport: Forge Config API Port 21.1.0
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		formations: Formations 1.0.2
		formationsnether: Formations Nether 1.0.5
		formationsoverworld: Formations Overworld 1.0.4
		framework: Framework 0.9.2
			org_javassist_javassist: javassist 3.29.2-GA
			org_reflections_reflections: reflections 0.10.2
		friendsandfoes: Friends&Foes 2.0.17
		fullturtlearmor: Full Turtle Armor 1.10.2
		geckolib: GeckoLib 4 4.6.3
		geophilic: Geophilic 3.1.1
		gigeresque: Gigeresque 0.6.10
		glitchcore: GlitchCore 2.1.0.0
			net_jodah_typetools: typetools 0.6.3
		gpumemleakfix: Gpu memory leak fix mod 1.21-1.8
		hearths: Hearths 1.0.1
		horseshoes: Horseshoes 1.2.3
		immediatelyfast: ImmediatelyFast 1.2.21+1.21.1
			net_lenni0451_reflect: Reflect 1.3.4
		inventorytotem: Inventory Totem 3.3
		iris: Iris 1.8.0-beta.3+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		ironladders: Iron Ladders 2.5.2
		jade: Jade 15.2.1+fabric
		jamlib: JamLib 1.0.11+1.21
			blue_endless_jankson: jankson 1.2.3
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 19.16.4.183
		justenoughbreeding: Just Enough Breeding 1.4.0
		keepmysoiltilled: Keep My Soil Tilled 2.4
		kilnreborn: Kiln Reborn 1.2.1-1.21
		laserbridges: Laser Bridges & Doors 1.21.1-2-fabric
		litematica: Litematica 0.19.50
		litematica_printer: Litematica Printer 7.2.1
		lootintegrations: Loot integration Mod 1.21-3.7
		make_bubbles_pop: Make Bubbles Pop 0.3.0-fabric
		malilib: MaLiLib 0.21.0
		mcpitanlib: MCPitanLib 2.4.0-1.21-fabric
			compatdatapacks76: CompatDatapacks 1.0.9.210-fabric
			org_yaml_snakeyaml: snakeyaml 2.0
		midnightlib: MidnightLib 1.6.3
		minecraft: Minecraft 1.21.1
		modernfix: ModernFix 5.19.3+mc1.21.1
		moonlight: Moonlight Lib 1.21-2.14.16
		mooshroomspawn: Mooshroom Spawn 3.6
		mooshroomtweaks: Mooshroom Tweaks 3.5
		morezombievillagers: More Zombie Villagers 3.6
		mousetweaks: Mouse Tweaks 2.26
		moveboats: Move Boats 3.4
		moveminecarts: Move Minecarts 3.6
		movingelevators: Moving Elevators 1.4.8
		mr_dungeons_andtaverns: Dungeons and Taverns 1-v4.3
		mr_vanilla_backpacks: Backpacks! EDIT 1
		musketmod: Musket Mod 1.5.2
		nametagtweaks: Name Tag Tweaks 3.8
		naturallychargedcreepers: Naturally Charged Creepers 3.5
		naturescompass: Nature's Compass 1.21.1-2.2.5-fabric
		netherdepthsupgrade: Nether Depths Upgrade fabric-3.1.8-1.21
		netherportalfix: NetherPortalFix 21.1.1
		nochatreports: No Chat Reports 1.21-v2.8.0
		noisium: Noisium 2.3.0+mc1.21-1.21.1
		notenoughanimations: NotEnoughAnimations 1.7.6
		nutritiousmilk: Nutritious Milk 3.4
		onsoulfire: On Soul Fire 1.21-r1
			cardinal-components-base: Cardinal Components API (base) 6.1.1
			cardinal-components-entity: Cardinal Components API (entities) 6.1.1
		pandalib: PandaLib 0.4.2
		paperbooks: Paper Books 3.5
		particlerain: Particle Rain 2.1.4
		passiveshield: Passive Shield 3.6
		philipsruins: Philip`s Ruins 1.21.1
		polymer-bundled: Polymer 0.9.13+1.21.1
			polymer-blocks: Polymer (Textured Blocks) 0.9.13+1.21.1
			polymer-common: Polymer (Common) 0.9.13+1.21.1
				packet_tweaker: Packet Tweaker 0.5.5+1.21
			polymer-core: Polymer (Core) 0.9.13+1.21.1
				polymer-networking: Polymer (Networking) 0.9.13+1.21.1
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.9.13+1.21.1
			polymer-resource-pack: Polymer (Resource Pack) 0.9.13+1.21.1
			polymer-virtual-entity: Polymer (Virtual Entity) 0.9.13+1.21.1
		purediscstrickytrials: Pure Discs - Tricky Trials 2.0.0
		puresmores: Pure S'mores 2.0.1
		rainbegoneritual: Rain Be Gone Ritual 3.4
		randombonemealflowers: Random Bone Meal Flowers 4.6
		randomsheepcolours: Random Sheep Colours 3.4
		realisticfirespread: Realistic Fire Spread 1.21-r1
		reborncore: Reborn Core 5.11.10
			team_reborn_energy: Energy 4.1.0
		recast: Recast 3.5
		refurbished_furniture: MrCrayfish's Furniture Mod: Refurbished 1.0.6
		reinfbarrel: Reinforced Barrels 2.6.0+1.21.1
			reinfcore: Reinforced Core 4.0.2+1.21.1
		reinfchest: Reinforced Chests 3.1.0+1.21.1
		reinfshulker: Reinforced Shulker Boxes 3.2.0+1.21.1
		replantingcrops: Replanting Crops 5.4
		repurposed_structures: Repurposed Structures 7.5.9+1.21.1-fabric
		reputation: Your Reputation 0.2.8+jade.1.21.1
		respawningshulkers: Respawning Shulkers 4.0
		rightclickharvest: Right Click Harvest 4.3.1+1.21
		scaffoldingdropsnearby: Scaffolding Drops Nearby 3.3
		sereneseasons: SereneSeasons 10.1.0.0
		shulkerdropstwo: Shulker Drops Two 3.4
		skeletonhorsespawn: Skeleton Horse Spawn 4.0
		sleepsooner: Sleep Sooner 4.6
		smallships: Small Ships 2.0.0-b1.5
		sodium: Sodium 0.6.0-beta.1+mc1.21
		spidersproducewebs: Spiders Produce Webs 3.5
		spyglass_improvements: Spyglass Improvements 1.5.7
		stackrefill: Stack Refill 4.5
		superbsteeds: Superb Steeds 1.21-r1
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17+b
		taxfreelevels: Tax Free Levels 1.3.12
		terrablender: TerraBlender 4.1.0.3
		universal-graves: Universal Graves 3.4.3+1.21
			common-protection-api: Common Protection API 1.0.0
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			placeholder-api: Placeholder API 2.4.1+1.21
			predicate-api: Predicate API 0.5.1+1.21
			server_translations_api: Server Translations API 2.3.1+1.21-pre2
			sgui: sgui 1.6.0+1.21
		visuality: Visuality 0.7.7+1.21
		wakes: Wakes 0.3.0+1.21.1
			com_github_jdiemke_delaunay-triangulator_delaunaytriangulator: DelaunayTriangulator 1.0.0
			satin: Satin 2.0.0
		waystones: Waystones 21.1.3
		weakerspiderwebs: Weaker Spiderwebs 3.7
		woodarmor: Wooden Armors (+ Stone Armor) 1.0.1
		wormhole: Wormhole (Portals) 1.1.16
		xaerominimap: Xaero's Minimap 24.4.0
		xaeroworldmap: Xaero's World Map 1.39.0
	Loaded Shaderpack: (off)
	Server Running: true
	Player Count: 1 / 8; [class_3222['supercid87'/8, l='ServerLevel[New World]', x=-2034.05, y=-31.01, z=-8382.38]]
	Active Data Packs: vanilla, fabric, additionalstructures, advancednetherite, balm-fabric (incompatible), basicweapons, beekeeperhut, biomesoplenty (incompatible), brickfurnace, bronze, bucketlib (incompatible), caffeinated, ceramicbucket, chalk, collective, craftsaddles, doggytalents (incompatible), dragonloot, emeraldequipment, enderitemod, exlinecopperequipment, explorerscompass, fabric-convention-tags-v2, farmersdelight, formationsnether, formationsoverworld, friendsandfoes, fullturtlearmor, geophilic, gigeresque (incompatible), hearths, horseshoes, ironladders, kilnreborn, laserbridges, lootintegrations (incompatible), moonlight, movingelevators (incompatible), mr_dungeons_andtaverns, mr_vanilla_backpacks, musketmod (incompatible), nametagtweaks, naturescompass, netherdepthsupgrade, paperbooks, philipsruins, porting_lib_base, porting_lib_gametest, porting_lib_item_abilities, porting_lib_tags, purediscstrickytrials, puresmores, refurbished_furniture (incompatible), reinfbarrel, reinfchest, reinfshulker, repurposed_structures, rightclickharvest, sereneseasons (incompatible), server_translations_api, smallships, spyglass_improvements, supermartijn642corelib (incompatible), terrablender (incompatible), universal-graves, waystones (incompatible), woodarmor, wormhole (incompatible), gigeresque:friendsandfoescompat (incompatible), $polymer-resources, moonlight:mods_dynamic_assets
	Available Data Packs: $polymer-resources, additionalstructures, advancednetherite, balm-fabric (incompatible), basicweapons, beekeeperhut, biomesoplenty (incompatible), brickfurnace, bronze, bucketlib (incompatible), bundle, caffeinated, ceramicbucket, chalk, collective, craftsaddles, doggytalents (incompatible), dragonloot, emeraldequipment, enderitemod, exlinecopperequipment, explorerscompass, fabric, fabric-convention-tags-v2, farmersdelight, formationsnether, formationsoverworld, friendsandfoes, fullturtlearmor, geophilic, gigeresque (incompatible), gigeresque:friendsandfoescompat (incompatible), hearths, horseshoes, ironladders, kilnreborn, laserbridges, lootintegrations (incompatible), moonlight, moonlight:mods_dynamic_assets, movingelevators (incompatible), mr_dungeons_andtaverns, mr_vanilla_backpacks, musketmod (incompatible), nametagtweaks, naturescompass, netherdepthsupgrade, paperbooks, philipsruins, porting_lib_base, porting_lib_gametest, porting_lib_item_abilities, porting_lib_tags, purediscstrickytrials, puresmores, refurbished_furniture (incompatible), reinfbarrel, reinfchest, reinfshulker, repurposed_structures, rightclickharvest, sereneseasons (incompatible), server_translations_api, smallships, spyglass_improvements, supermartijn642corelib (incompatible), terrablender (incompatible), trade_rebalance, universal-graves, vanilla, waystones (incompatible), woodarmor, wormhole (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -534299007222217076
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.16.3-1.21.1

**Comment by AzureDoom** [comment]
Easy fix, will be released in the next day or so

**Comment by supercid87** [comment]
Nice!
