### ISSUE TITLE
Game crashes when the egg opens

### ISSUE THREAD

**Issue by furMASTiK** [cybercat-mods/gigeresque#290]
The game crashes everytime a facehugger is about to spawn. Its spawn egg doesnt work, but if you place a facehugger egg and get close to it so it opens, the game crashes. Here the error log:

The game crashed whilst ticking entity
Error: java.lang.IllegalStateException: Entity class mods.cybercat.gigeresque.common.entity.impl.classic.FacehuggerEntity has not defined synched data value 29

**Comment by AzureDoom** [comment]
Dupe of #287, closing this one.
