### ISSUE TITLE
Сlassic alien behavior

### ISSUE THREAD

**Issue by derasell** [cybercat-mods/gigeresque#292]
There is no random walking, if there are no targets, then it never moves. The system for capturing victims for egmorphing is also broken. an alien simply cannot place its victim in an egmorphing web. The alien does not use crawling, which means the alien will not be able to reach the player if there is no space 3 blocks high

**Comment by AzureDoom** [comment]
Please confirm the mc and mod version you are testing please.

**Comment by AzureDoom** [comment]
Please reopen this with the required info, a temple is now provided for this.
