### ISSUE TITLE
Alien behavior

### ISSUE THREAD

**Issue by derasell** [cybercat-mods/gigeresque#293]
mod version: fabric 0.7.1
Minecraft: 1.21.1

There is no random walking, if there are no targets, then it never moves. The system for capturing victims for egmorphing is also broken. an alien simply cannot place its victim in an egmorphing web. The alien does not use crawling, which means the alien will not be able to reach the player if there is no space 3 blocks high.

**Comment by AzureDoom** [comment]
Please fill out the full form, as stated on it.
