### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Craftingcat99** [cybercat-mods/gigeresque#296]
***ALL INFO MUST BE FILLED IN OR THE ISSUE WILL BE CLOSED AS INVALID***

**Minecraft Info:**
Minecraft Version: 1.20.1
Modloader version: forge 47.3.10
Mod version: 0.5.71

**Describe the bug**
Alien and Runner(the only ones i tested so far) seem to be unable to walk up 1 block elevations once the fixated a potential prey mob

**To Reproduce**
1. open new superflat world
2. /fill a ~20x20 area on top of the floor
3. Spawn a pig on the middle of the platform and an alien next to the platform
4. Alien will most likely get stuck in front of/slightly under the first elevated block

![2024-09-19_22 38 58](https://github.com/user-attachments/assets/9caf9d63-4495-40b4-8b08-3b65536f6b9a)
![2024-09-19_22 39 00](https://github.com/user-attachments/assets/f68871d6-1ea2-4f65-97d2-4dd0627b7142)
![2024-09-19_22 39 07](https://github.com/user-attachments/assets/10331edc-c899-4974-adc2-24ae9895a013)
![2024-09-19_22 39 13](https://github.com/user-attachments/assets/fe77b7fa-f44d-4904-abd2-86563502d9e4)
![2024-09-19_22 46 16](https://github.com/user-attachments/assets/8c593f76-02c1-4afb-9ec3-d5f212fff8cf)

**Comment by Craftingcat99** [comment]
0.5.71 is the latest forge compatible version as far as i know, or have i missed something? because i found a similar bug reported as completed but still can't figure out, why i cant get the alien to climb a 1 block elevation

**Comment by AzureDoom** [comment]
1.20.1 is not updated.

**Comment by Craftingcat99** [comment]
Can i use the later versions on forge or am i stuck using fabric/neoforge if I want to play the most up to date version of this mod?

**Comment by AzureDoom** [comment]
Forge is dead, let it die.
