### ISSUE TITLE
[BUG] Classic xenomorph's behavior

### ISSUE THREAD

**Issue by kukumbersimp** [cybercat-mods/gigeresque#297]
***ALL INFO MUST BE FILLED IN OR THE ISSUE WILL BE CLOSED AS INVALID***

**Minecraft Info**
Minecraft Version: 1.21.1
Modloader version: fabric api 0.104.0
Mod version: 0.7.4

**Description 1**

Classic grown aliens don't move, they start moving when a prey is near them only. Alien sees any other creature and then starts walking, jumping or running towards it.

**Steps to reproduce the behavior:**

1. Get the item 'Alien Spawn Egg' (or get 'Alien Egg Spawn Egg' and create the cycle)
2. Place it in the inventar
3. Spawn the creature (or create alien's cycle, grow up xenomorph)
4. See how it only turns around and doesn't walk

Two first screenshots show how others from this mode walk around and classic xenomorph just stands still
![screenshot 1](https://github.com/user-attachments/assets/8e9405e2-eaab-41b5-9668-ad9fbf4e2d28)
![screenshot 2](https://github.com/user-attachments/assets/62e1fea8-77a0-4b66-8df6-548e838339e8)

**Description 2**

Classic alien doesn't climb on the surfaces so get a prey that is placed higher than two blocks is impossible for xenomorph

**Steps to reproduce the behavior:**

1. Build three blocks up
2. Build small cage of thin glass so a prey couldn't jump off and run away
3. Get the items 'Villager Spawn Egg' and 'Alien Spawn Egg'
4. Place these spawn eggs in the inventar
5. Spawn villager on those three blocks
6. Spawn classic alien
7. See how xenomorph just bumps into blocks and does nothing

The third screenshot
![screenshot 3](https://github.com/user-attachments/assets/dfc92c12-c812-44c5-b9cd-4f07a4ca5165)

**Description 3**

Classic alien can't put a creature into nest resing web for eggmorphing. For example xenomorph attacks a villager, grabs him and walks around with him until the animation of attack with second jaw starts playing killing this villager or until villager suffocates in blocks

**Steps to reproduce the behavior:**

1. Get the item 'Nest Resing Web (Cross)'
2. Place this item in the inventar
3. Put it on the surface (or let xenomorph do it in its nest)
4. Get items 'Villager Spawn Egg' and 'Alien Spawn Egg'
5. Place these spawn eggs in the inventar
6. Spawn a classic alien
7. Spawn a villager
8. See how a classic alien run towards villager, grabs him and starts walking around, going away from the web

The fourth screenshot
![screenshot 4](https://github.com/user-attachments/assets/fafb15c3-f17d-4d0a-bb64-38a85a846bba)

(English isn't my native language, sorry for mistakes)

**Comment by AzureDoom** [comment]
In the future, please open an issue for only 1 at a time. The last one is not a bug, it is not a 100% chance. The 2nd is coming in a future update. and the First one is normal. That's just it running the stasis code more often, which happens and is a normal part of it's code.
