### ISSUE TITLE
Sitting idols/xenos facing the incorrect direction

### ISSUE THREAD

**Issue by AverageUser67** [cybercat-mods/gigeresque#298]
**Minecraft Info:**
Minecraft Version: 1.21.1
Modloader version: neoforge-21.1.57
Mod version: 0.7.5

**Describe the bug**
Exactly the title. Sitting idols and xenomorphs in the black goo tubes/containment tank things all face north

**To Reproduce**
1. Play the mod
2. Go to a dungeon
3. Look in egg pits/bio-engineering room tube
4. Staring at wall intensifies

**Screenshots**
![2024-09-21_10 36 56](https://github.com/user-attachments/assets/97bed845-1a6c-448e-8f6b-c624b6d08257)
I'm pretty sure that the gig dungeon generator just doesn't know how to place things with direction- this happens with sarcophagi and the like too

**Comment by AzureDoom** [comment]
This is intended at this time
