### ISSUE TITLE
[BUG] Containers has no loot generated

### ISSUE THREAD

**Issue by SwiftSniffer** [cybercat-mods/gigeresque#299]
**Minecraft Info:**
Minecraft Version: 1.21.1
Modloader version: Fabric
Mod version: 0.7.5

**Describe the bug**
No containers in the dungeons has loot generated inside. They are all empty. From statues, to sarcophagus, to jars.

**To Reproduce**
1. Boot 0.7.5 for Fabric.
2. Locate a dungeon
3. Open a container

**Screenshots**
It is self-explanatory.

**Comment by AzureDoom** [comment]
Closing as fixed in the next update as per testing done by builders/testers.
