### ISSUE TITLE
[BUG] Strange stun during grab

### ISSUE THREAD

**Issue by SwiftSniffer** [cybercat-mods/gigeresque#300]
**Minecraft Info:**
Minecraft Version: 1.21.1
Modloader version: Fabric
Mod version: 0.7.5

**Describe the bug**
When the Alien grab an entity, they freeze on the spot, while the target spin. This continues until the target dies from a headbite.

**To Reproduce**
1. Spawn an Alien
2. Let it target a mob and grab it
3. Enjoy

**Screenshots**
A video:

https://github.com/user-attachments/assets/b86a0541-dea6-488e-b13f-e396e2e87fe9

**Comment by AzureDoom** [comment]
Closing as fixed in the next update as per testing done by builders/testers.
