### ISSUE TITLE
[BUG] Chestbursters follows you

### ISSUE THREAD

**Issue by SwiftSniffer** [cybercat-mods/gigeresque#302]
**Minecraft Info:**
Minecraft Version: 1.21.1
Modloader version: Fabric
Mod version: 0.7.5

**Describe the bug**
Whether you give birth to one, or spawn one through creative mode, any and all chestburster types will follow you around, like a happy family. That also applies if you try to kill them. They do not, flee, do not bite back, they just follow you like you're their mother.

**To Reproduce**
1. Give birth or spawn chestburster, any type.

**Screenshots**
![image](https://github.com/user-attachments/assets/6153f1cc-41c1-43bf-9eda-64d0f0d5141a)

**Comment by AzureDoom** [comment]
Closing as fixed in the next update as per testing done by builders/testers.
