### ISSUE TITLE
[BUG] Wearing armor make you survive being chestbursted

### ISSUE THREAD

**Issue by SwiftSniffer** [cybercat-mods/gigeresque#303]
**Minecraft Info:**
Minecraft Version: 1.21.1
Modloader version: Fabric
Mod version: 0.7.5

**Describe the bug**
Armor is taken into account when calculating the damage dealt by the terminal of the impregnation effect.
Meaning, any full armor leaves you with enough health to survive a chestburster exiting you. The stronger/most enchanted, the less health you will lose.

**To Reproduce**
1. Wear any armor.
2. Inflict yourself with impregnation effect.
3. Witness.

**Screenshots**
This is p4 netherite armor. It removed one heart. For comparison, a full leather armor leaves you with one heart left.
![image](https://github.com/user-attachments/assets/a2d4e616-a0fa-4de9-b024-172c1e4745de)

**Comment by AzureDoom** [comment]
Closing as fixed in the next update as per testing done by builders/testers.
