### ISSUE TITLE
[BUG] Alien is unable to break blocks

### ISSUE THREAD

**Issue by SwiftSniffer** [cybercat-mods/gigeresque#304]
**Minecraft Info:**
Minecraft Version: 1.21.1
Modloader version: Fabric
Mod version: 0.7.5

**Describe the bug**
The Alien can not break soft blocks (such as glass) by smashing those. Furthermore, they can not break tougher block (such as stone) through the acid spill method. This happens even when the Alien detects a target on the other side. The most obvious case is in the dungeon with the hub room.

**To Reproduce**
1. Check out the dungeon's hub room with the Alien in the glass tube. Alternatively, spawn an alien, surround it with any blocks.
2. Spawn a target nearby, or be the target yourself.

**Screenshots**
![image](https://github.com/user-attachments/assets/ced17f0f-15f9-4da4-b2a8-88d8d1e16a29)

**Comment by AzureDoom** [comment]
Closing as fixed in the next update as per testing done by builders/testers.
