### ISSUE TITLE
[BUG] Unknown crash related to Gigeresque

### ISSUE THREAD

**Issue by SkeirBoreal** [cybercat-mods/gigeresque#306]
**Minecraft Info:**
Minecraft Version: 1.20.1
Modloader version: Fabric
Mod version: 0.7.5

**Describe the bug**
When encountering the Warden (and running around aimlessly) I eventually decided to shoot the warden with an arrow, then immediately got a crash. Now everytime I load in those chunks with the warden I get some crash report, which includes Gigeresque in the stack trace. I haven't even once encountered a Gigeresque structure on my server.

**To Reproduce**
1. Go to a snowy biome and try finding an ancient city or sculk biomes.
2. Get the warden to spawn then try shooting it with a bow and arrow.

**Screenshots**
![notepad++_okSY5aH61J](https://github.com/user-attachments/assets/3f5a0ee1-d95c-4717-8b52-bc3cd706c964)

[crash-2024-09-30_04.35.03-server.txt](https://github.com/user-attachments/files/17184170/crash-2024-09-30_04.35.03-server.txt)

**Comment by AzureDoom** [comment]
1.20.1 is not supported nor maintained
