### ISSUE TITLE
do not assert

### ISSUE THREAD

**Issue by ryleu** [cybercat-mods/gigeresque#307]
https://github.com/cybercat-mods/gigeresque/blob/a75baff29953774c65831278b64a17e0d7280025/src/main/java/mods/cybercat/gigeresque/mixins/common/entity/WardenEntityMixin.java#L18

This causes weird issues with many different mods. `entity` very well may be null, so do a proper null check.

Here's a log if you still aren't sure it matters: https://mclo.gs/HgwldKf#L3829

**Comment by AzureDoom** [comment]
This is fixed in 1.21+. See: https://github.com/cybercat-mods/gigeresque/blob/1.21.x/common/src/main/java/mods/cybercat/gigeresque/mixins/common/entity/WardenEntityMixin.java#L17

1.20.1 is abandoned and no longer updated

**Comment by ryleu** [comment]
if i make a PR will you merge it?

**Comment by ryleu** [comment]
made #308 
i still use 1.20.1 and per your license, i can't distribute a modified copy of the mod

**Comment by AzureDoom** [comment]
I will merge and release here when I can. Please note, however, that due to Forge 1.20.1 brain issues, only the fabric version will be pushed, so you will need to swap from the forge-marked jar to the fabric one manually.
