### ISSUE TITLE
[BUG] Facehuggers Pursue, but Cannot Attach to Spiders

### ISSUE THREAD

**Issue by whales0ng** [cybercat-mods/gigeresque#309]
**Minecraft Info:**
Minecraft Version: 1.21.1
Modloader version: Fabric 0.107.0+1.21.1
Mod version: Fabric 0.7.5

**Describe the bug**
Facehuggers will pursue spiders, but are unable to attach to them. They follow the spider closely until the spider is removed/dies, after which they resume normal behavior.

**To Reproduce**
1. Spawn a Facehugger or allow one to spawn from an Alien Egg with a spider in closest proximity.

**Screenshots**
N/A

**Comment by AzureDoom** [comment]
They are following the sounds, but spiders are not a valid host is all. This isn't really a bug but just how the sound tracking is done.
