### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MrLeon26** [cybercat-mods/gigeresque#310]
***ALL INFO MUST BE FILLED IN OR THE ISSUE WILL BE CLOSED AS INVALID***

**Minecraft Info:**
Minecraft Version: 1.20.1
Modloader version: CurseForge
Mod version: 0.5.71

**Describe the bug**
It seems like this amazing mod is very buggy in 1.20.1 the xenomorphs keep getting stuck in corners and can barely move towards their enemy, their very easy to escape. And the face huggers have the same problem ish, they get stuck in corners and cant ''face hug'' their target. If they somehow do manage to attach to the target they cant sit still on the hosts face and start spinning

**To Reproduce**

I know nothing about codding, but I know you guys are doing your best in making the mod as sustainable as possible, only if possible, please focus on this problem since 1.20.1 is the biggest version for modding. Most mods are made for 1.20.1

**Screenshots**

![Screenshot 2024-08-17 111203](https://github.com/user-attachments/assets/daced092-c8b0-499d-8ffb-90ad66a46979)
![Screenshot 2024-08-17 111101](https://github.com/user-attachments/assets/12c04c3c-6382-41d9-b891-441f0d5ec737)

**Comment by AzureDoom** [comment]
1.21.1 is the only maintained version

**Comment by MrLeon26** [comment]
I completely understand. But recently Minecraft announced that they will start releasing more updates than usual, and if you want your mod to be on each version that is going to be a pain. I don't want to tell you what to do, but if I were you I would focus on 1.20.1 which is the most used version, especially for modding, and after the mod works very solidly then you can focus on the most played versions.  1.21.1 might not be a very used version for modding (sorry for the essay)

**Comment by AzureDoom** [comment]
Cool story, don't care, we are focusing on the version we want, which is 1.21.1. Don't care if you don't like.
