### ISSUE TITLE
Facehuggers twitch between climbing on the ceiling or walking on the floor

### ISSUE THREAD

**Issue by cuz04** [cybercat-mods/gigeresque#45]
Thought it was a bit funny, though.
https://user-images.githubusercontent.com/47876902/166134433-7c45c08b-3080-4a46-94b0-888afe7e1438.mp4

**Comment by Rainyredman1234** [comment]
Xenos do similar with wall climbs and cielings too but I thought it was a little too obvious and common for making it's own issue post

**Comment by AzureDoom** [comment]
Fixed in upcoming rewrite.
