### ISSUE TITLE
Game keeps crashing

### ISSUE THREAD

**Issue by Dinocroc22** [cybercat-mods/gigeresque#50]
This is what it says 

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'gigeresque'!
Exit Code: -1

idk what that means, please help

**Comment by Dinocroc22** [comment]
[crash-2022-05-22_21.03.25-client.txt](https://github.com/cybercat-mods/gigeresque/files/8750629/crash-2022-05-22_21.03.25-client.txt)

**Comment by AzureDoom** [comment]
```
Caused by: java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/ConfigData

```
