### ISSUE TITLE
face hugger is a magician

### ISSUE THREAD

**Issue by RaccRegimist** [cybercat-mods/gigeresque#51]
while a facehugger is on the ceiling it likes to disappear into the block above it

**Comment by AzureDoom** [comment]
![image](https://user-images.githubusercontent.com/7415711/171970034-b585942e-788b-4dc9-910d-1f20f76cc818.png)
It's just his ninja way lol

**Comment by AzureDoom** [comment]
Fixed in the upcoming update.
