### ISSUE TITLE
Xeno gets lazy and tries to phase through the ground to get home

### ISSUE THREAD

**Issue by sonofabaconator** [cybercat-mods/gigeresque#52]
I've noticed that sometimes when a Xenomorph kidnaps someone and his nest is in a hill or something, he tries to go directly into the nest by standing over it on the hill... which looks hilarious to see this guy spinning in circles on a hill with a bouncing chicken on his back... probably just a pathfinding issue that you are already aware of by now... just wanted to say something just in case.

**Comment by AzureDoom** [comment]
Yeah, the whole system is gutted and in the middle of a rewrite currently.

**Comment by sonofabaconator** [comment]
Ahh... I see... well keep up the good work, this mod is amazing and I can't wait for future content!
