### ISSUE TITLE
When i go deep into the black goo it crashes

### ISSUE THREAD

**Issue by Crispeuw360** [cybercat-mods/gigeresque#54]
when i crawl, with the fabric mod crawl, it crashes

**Comment by AzureDoom** [comment]
This requires a crash log, as stated twice in discord.

**Comment by shadeproject** [comment]
when you go into black goo that is more than 1 block deep the game crashes anyway

**Comment by Crispeuw360** [comment]
[crash-2022-06-25_23.27.58-client.txt](https://github.com/cybercat-mods/gigeresque/files/8985614/crash-2022-06-25_23.27.58-client.txt)

**Comment by Crispeuw360** [comment]
> This requires a crash log, as stated twice in discord.

there is the crash report

**Comment by AzureDoom** [comment]
Fixed in upcoming update.
