### ISSUE TITLE
Lama's are killing Face huggers

### ISSUE THREAD

**Issue by shadeproject** [cybercat-mods/gigeresque#61]
when the face hugger tries to face hug a lama, the lama kind of pull it around, and then it just drops dead to the ground. this mostly takes a couple of seconds. the lama is also not impregnated from that. and the lama gets some sort of invincibility to one hit with a sword.

**Comment by AzureDoom** [comment]
Fixed in the rewrite already. Pending a few more ai changes, a build is aimed for a week or so.
