### ISSUE TITLE
Aquatic xenomorph - idle animation bug

### ISSUE THREAD

**Issue by Tornado4Team** [cybercat-mods/gigeresque#66]
Aquatic xenomorph's idle animation pushes the model down if it's on the surface - in water, it works fine as long as it will decide to use idle animation instead of swimming one. 
[Xeno in water gif](
https://i.gyazo.com/59d34fd51e363fcf42f76440eb829b4a.mp4)
![image](https://user-images.githubusercontent.com/17530727/180650638-ef8de472-8511-4fae-ac6d-d03bb25fa300.png)

**Comment by AzureDoom** [comment]
Fixed in next patch.
