### ISSUE TITLE
Facehuggers don't attack anything if spawned by an alien egg

### ISSUE THREAD

**Issue by Tornado4Team** [cybercat-mods/gigeresque#67]
Facehuggers behave in different ways based on how they were spawned.
Spawned by an alien egg - they don't attack anything around https://i.gyazo.com/d208a6bcb8e4261c2809671439647680.mp4
Spawned by command/spawn egg - an instant attack on the possible host (player) https://i.gyazo.com/9134683a45f95506eed866c9c2d5e817.mp4

**Comment by AzureDoom** [comment]
Fixed in next patch
