### ISSUE TITLE
Impregnation isn't applied by facehugger

### ISSUE THREAD

**Issue by ImpulsiveLass** [cybercat-mods/gigeresque#69]
The particles effect is missing for impregnation and a facehugger will immediately go on the mob after the last one has fell off.
The mobs don't burst after the time would run out as well

https://user-images.githubusercontent.com/92990441/185508795-83372119-e0d9-460a-8e5c-7a52bbf19590.mp4

.

**Comment by sonofabaconator** [comment]
Hmmm... Nice issue
