### ISSUE TITLE
i tried to play gigeresque and when i started it crashed and this was the crash report 

### ISSUE THREAD

**Issue by krokoboi** [cybercat-mods/gigeresque#76]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabric-networking-api-v1'!

**Comment by ImpulsiveLass** [comment]
Sounds like fabric networking api caused it

**Comment by AzureDoom** [comment]
Please ensure you are fully updated on Fabric and Fabric API

**Comment by krokoboi** [comment]
im sorry i forgot to install fabric api!
