### ISSUE TITLE
The game crashes on start

### ISSUE THREAD

**Issue by jedimoo** [cybercat-mods/gigeresque#79]
When i try to start the game it crashes with "Exit Code: 1"

**Comment by AzureDoom** [comment]
Ensure you have all proper requirements.

**Comment by jedimoo** [comment]
I have Cloth-Config ,Fabric-api and Gekolib-Fabric

**Comment by AzureDoom** [comment]
Those are not correct

**Comment by jedimoo** [comment]
what do i need then

**Comment by AzureDoom** [comment]
1.19.2 and latest Geckolib. Oh and actual logs
