### ISSUE TITLE
Error when attempting to play chest burster hatching noise

### ISSUE THREAD

**Issue by NobleSaurusRex** [cybercat-mods/gigeresque#83]
I'm playing with the mod on a server I run, and whenever a chest burster hatches from its host (I tested both a player and villager) it kicks me from the server and won't let me rejoin until the server restarts. I think that it's trying to play a sound for when it hatches, but it can't find the sound, or doesn't know what to do with it. When restarting the server, it lets me join back, but instead of the expected one, there are four chest bursters where the host dies. Here is the error message when trying to join the server:

java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3414@385fa66c' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]

I was playing on build #76, so apologies if this has been fixed in the newest version, I just didn't have time to test out the newest version with this bug at the time of posting this bug report.

**Comment by AzureDoom** [comment]
Please test latest as this was fixed here https://github.com/cybercat-mods/gigeresque/commit/2e1166a0ccb0392eae77f3d299963793f76c8948

**Comment by NobleSaurusRex** [comment]
Thanks!
