### ISSUE TITLE
Xenos are confused by vibrations

### ISSUE THREAD

**Issue by ImpulsiveLass** [cybercat-mods/gigeresque#86]
Xenomorphs seem to get confused with the vibrations as in they will prioritize following vibrations or other mobs over eggmorphing the mob they are carrying, they also seem to ignore vibrations at times so I recorded a video of one getting "confused" since its hard to determine exactly whats happening.
https://streamable.com/jgwiha

**Comment by AzureDoom** [comment]
Fixed in latest build released on CF.
