### ISSUE TITLE
trying to fire a flamethrower at a runner alien

### ISSUE THREAD

**Issue by shadeproject** [cybercat-mods/gigeresque#90]
Error: java.lang.ClassCastException: class mod.azure.hwg.entity.projectiles.FlameFiring cannot be cast to class net.minecraft.class_1309 (mod.azure.hwg.entity.projectiles.FlameFiring and net.minecraft.class_1309 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @6a396c1e)

**Comment by AzureDoom** [comment]
Full log

**Comment by shadeproject** [comment]
its a bug with HWG not gigeresque, sorry for reporting that here
