### ISSUE TITLE
rooms in gig dungeons are not covered by stone

### ISSUE THREAD

**Issue by shadeproject** [cybercat-mods/gigeresque#91]
![2022-12-23_15 10 44](https://user-images.githubusercontent.com/104649995/209341763-6a0b97ff-e906-453f-ae1e-1be2fea196d8.png)

**Comment by AzureDoom** [comment]
What version?

**Comment by shadeproject** [comment]
the newest alpha for Minecraft version 1.19.3

**Comment by UYGYDG** [comment]
hey in mod was xenomorph qeen ?

**Comment by AzureDoom** [comment]
Is working for me correctly so closing for now
