### ISSUE TITLE
Only humanoid hosts are eggmorphable

### ISSUE THREAD

**Issue by FakeACat** [cybercat-mods/gigeresque#99]
Animals that host runners (cows, pigs, sheep etc) cannot be eggmorphed. Unsure if this is intentional but it doesn't make much sense so I assume not. I checked the code and the cause looks simple, eggmorphing only occurs if ConfigAccessor.isTargetAlienHost(mob) returns true which is only the case if the mob is a host for a classic alien

**Comment by AzureDoom** [comment]
It is indeed intended for the moment to help limit testing at this time, as the main focus has been the classic xenomorph
